// Authentication: login page + verified alumni registration.
const auth = {
  en: {
    auth: {
      brand: {
        network: "KPU Alumni Network",
        university: "Kabul Polytechnic University",
      },
      login: {
        eyebrow: "Sign in to your account",
        headingLine1: "Welcome back to the",
        headingHighlight: "KPU community.",
        intro:
          "Reconnect with classmates, discover career opportunities, and stay updated with everything happening at Kabul Polytechnic University.",
        cardBadge: "Sign In",
        cardTitle: "Welcome back",
        cardSubtitle: "Enter your credentials to access your account.",
        emailLabel: "Email Address",
        emailPlaceholder: "you@example.com",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter your password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign In",
        signingIn: "Signing in…",
        newToAlumni: "New to KPU Alumni?",
        createVerified: "Create a verified account",
        verifiedNote: "Verified through MIS records · Secure & confidential",
      },
      benefits: {
        resources: "Access exclusive alumni resources",
        network: "Network with 10,000+ KPU graduates",
        career: "Career opportunities and mentorship",
        events: "Alumni events and reunions",
      },
      errors: {
        loginFailed: "Login failed",
        loginFailedRetry: "Login failed. Please try again.",
        universityIdRequired: "University ID is required",
        studentNotFound: "Student not found. Please check your University ID.",
        notGraduated: "You cannot register yet — you are still an enrolled student and have not graduated. Registration is only available after you graduate.",
        tazkiraRequired: "Tazkira number is required",
        tazkiraFailed:
          "Tazkira verification failed. Please check your tazkira number.",
        universityIdNotFound:
          "University ID not found in our records. Please check your University ID first.",
        tazkiraNotFound:
          "Tazkira number not found in our records. Please check your tazkira number.",
        mismatch:
          "University ID and Tazkira number do not match the same student in our records.",
        registrationFailed: "Registration failed. Please try again.",
        searchProfileFirst: "Please search for your student profile first",
      },
      register: {
        heroBadge: "Verified Registration",
        heroTitle: "Create Your KPU Alumni Account",
        heroSubtitle:
          "Verified through official MIS records — secure, exclusive, and trusted.",
        stepFindProfile: "Find Profile",
        stepAccount: "Account",
        stepVerify: "Verify",
        verified: "Verified",
        successTitle: "Registration successful!",
        successBody:
          "Welcome to the verified alumni network. Redirecting to your profile…",
        failTitle: "Registration failed",
        step1Title: "Find your student profile",
        step1Subtitle:
          "Enter your University ID to verify against our MIS records.",
        universityIdLabel: "University ID",
        universityIdPlaceholder: "e.g. KPU-2018-1234",
        searching: "Searching…",
        searchProfile: "Search Profile",
        profileFound: "Profile found in MIS records",
        fieldFullName: "Full Name",
        fieldName: "Name",
        fieldFatherName: "Father Name",
        fieldGrandfatherName: "Grandfather Name",
        fieldUniversityId: "University ID",
        fieldFaculty: "Faculty",
        fieldDepartment: "Department",
        fieldGraduationYear: "Graduation Year",
        fieldPhoneNumber: "Phone Number",
        notAvailable: "N/A",
        step2Title: "Account information",
        step2Subtitle: "Choose the credentials you'll use to sign in.",
        emailLabel: "Email Address",
        emailPlaceholder: "you@example.com",
        passwordLabel: "Password",
        passwordPlaceholder: "Choose a strong password",
        confirmPasswordLabel: "Confirm Password",
        confirmPasswordPlaceholder: "Re-enter your password",
        strength: "Strength",
        strengthWeak: "Weak",
        strengthFair: "Fair",
        strengthGood: "Good",
        strengthStrong: "Strong",
        passwordRequirementsLabel: "Password requirements:",
        passwordRequirements:
          "at least 8 characters, one capital letter, one number, and one special character (@$!%*?&).",
        step3Title: "Professional information",
        step3Subtitle: "Optional — help fellow alumni get to know you.",
        jobTitleLabel: "Current Job Title",
        jobTitlePlaceholder: "e.g. Senior Software Engineer",
        companyLabel: "Current Company",
        companyPlaceholder: "e.g. Google",
        locationLabel: "Location",
        locationPlaceholder: "e.g. Kabul, Afghanistan",
        linkedinLabel: "LinkedIn Profile",
        linkedinPlaceholder: "https://linkedin.com/in/…",
        profileImageLabel: "Profile Image",
        coverImageLabel: "Cover Image",
        bioLabel: "Bio",
        bioPlaceholder:
          "Tell fellow alumni about your journey, interests, and what you're working on…",
        submitHintReady:
          "You'll be asked to verify your identity with a tazkira number after clicking",
        submitHintReadyButton: "Complete Registration",
        submitHintStart:
          "Search your University ID above to start the verification flow.",
        registering: "Registering…",
        completeRegistration: "Complete Registration",
        alreadyHaveAccount: "Already have an account?",
        signInInstead: "Sign in instead",
      },
      tazkira: {
        finalStep: "Final Step",
        title: "Verify your identity",
        introBefore: "Please enter your",
        introBold: "tazkira number",
        introAfter:
          "to confirm you are the student we found in the MIS records. This is a one-time verification.",
        label: "Tazkira Number",
        placeholder: "Enter your tazkira number",
        cancel: "Cancel",
        verifying: "Verifying…",
        verifyAndRegister: "Verify & Register",
      },
    },
  },

  da: {
    auth: {
      brand: {
        network: "شبکه فارغان KPU",
        university: "پوهنتون پولیتخنیک کابل",
      },
      login: {
        eyebrow: "به حساب خود وارد شوید",
        headingLine1: "به جامعه KPU",
        headingHighlight: "خوش آمدید.",
        intro:
          "با همصنفان خود دوباره ارتباط برقرار کنید، فرصت‌های شغلی را کشف کنید و از تمام رویدادهای پوهنتون پولیتخنیک کابل آگاه بمانید.",
        cardBadge: "ورود",
        cardTitle: "خوش آمدید",
        cardSubtitle: "برای دسترسی به حساب خود، اطلاعات ورود را وارد کنید.",
        emailLabel: "آدرس ایمیل",
        emailPlaceholder: "you@example.com",
        passwordLabel: "رمز عبور",
        passwordPlaceholder: "رمز عبور خود را وارد کنید",
        rememberMe: "مرا به خاطر بسپار",
        forgotPassword: "رمز عبور را فراموش کرده‌اید؟",
        signIn: "ورود",
        signingIn: "در حال ورود…",
        newToAlumni: "تازه به فارغان KPU پیوسته‌اید؟",
        createVerified: "ایجاد حساب تأیید‌شده",
        verifiedNote: "تأیید‌شده از طریق سوابق MIS · امن و محرمانه",
      },
      benefits: {
        resources: "دسترسی به منابع اختصاصی فارغان",
        network: "ارتباط با بیش از ۱۰٬۰۰۰ فارغ KPU",
        career: "فرصت‌های شغلی و رهنمایی",
        events: "رویدادها و گردهمایی‌های فارغان",
      },
      errors: {
        loginFailed: "ورود ناکام شد",
        loginFailedRetry: "ورود ناکام شد. لطفاً دوباره تلاش کنید.",
        universityIdRequired: "آی‌دی پوهنتون الزامی است",
        studentNotFound: "محصل یافت نشد. لطفاً آی‌دی پوهنتون خود را بررسی کنید.",
        notGraduated: "شما هنوز نمی‌توانید ثبت‌نام کنید — شما هنوز محصل فعال هستید و فارغ نشده‌اید. ثبت‌نام تنها پس از فراغت ممکن است.",
        tazkiraRequired: "شماره تذکره الزامی است",
        tazkiraFailed:
          "تأیید تذکره ناکام شد. لطفاً شماره تذکره خود را بررسی کنید.",
        universityIdNotFound:
          "آی‌دی پوهنتون در سوابق ما یافت نشد. لطفاً ابتدا آی‌دی پوهنتون خود را بررسی کنید.",
        tazkiraNotFound:
          "شماره تذکره در سوابق ما یافت نشد. لطفاً شماره تذکره خود را بررسی کنید.",
        mismatch:
          "آی‌دی پوهنتون و شماره تذکره با یک محصل واحد در سوابق ما مطابقت ندارند.",
        registrationFailed: "ثبت‌نام ناکام شد. لطفاً دوباره تلاش کنید.",
        searchProfileFirst: "لطفاً ابتدا پروفایل محصلی خود را جستجو کنید",
      },
      register: {
        heroBadge: "ثبت‌نام تأیید‌شده",
        heroTitle: "حساب فارغ KPU خود را ایجاد کنید",
        heroSubtitle:
          "تأیید‌شده از طریق سوابق رسمی MIS — امن، اختصاصی و قابل اعتماد.",
        stepFindProfile: "یافتن پروفایل",
        stepAccount: "حساب",
        stepVerify: "تأیید",
        verified: "تأیید‌شده",
        successTitle: "ثبت‌نام موفقانه انجام شد!",
        successBody:
          "به شبکه فارغان تأیید‌شده خوش آمدید. در حال انتقال به پروفایل شما…",
        failTitle: "ثبت‌نام ناکام شد",
        step1Title: "پروفایل محصلی خود را بیابید",
        step1Subtitle:
          "آی‌دی پوهنتون خود را برای تأیید با سوابق MIS ما وارد کنید.",
        universityIdLabel: "آی‌دی پوهنتون",
        universityIdPlaceholder: "مثلاً KPU-2018-1234",
        searching: "در حال جستجو…",
        searchProfile: "جستجوی پروفایل",
        profileFound: "پروفایل در سوابق MIS یافت شد",
        fieldFullName: "نام کامل",
        fieldName: "نام",
        fieldFatherName: "نام پدر",
        fieldGrandfatherName: "نام پدرکلان",
        fieldUniversityId: "آی‌دی پوهنتون",
        fieldFaculty: "پوهنځی",
        fieldDepartment: "دیپارتمنت",
        fieldGraduationYear: "سال فراغت",
        fieldPhoneNumber: "شماره تماس",
        notAvailable: "نامعلوم",
        step2Title: "معلومات حساب",
        step2Subtitle: "اطلاعاتی را که برای ورود استفاده می‌کنید انتخاب کنید.",
        emailLabel: "آدرس ایمیل",
        emailPlaceholder: "you@example.com",
        passwordLabel: "رمز عبور",
        passwordPlaceholder: "یک رمز عبور قوی انتخاب کنید",
        confirmPasswordLabel: "تأیید رمز عبور",
        confirmPasswordPlaceholder: "رمز عبور را دوباره وارد کنید",
        strength: "قدرت",
        strengthWeak: "ضعیف",
        strengthFair: "متوسط",
        strengthGood: "خوب",
        strengthStrong: "قوی",
        passwordRequirementsLabel: "نیازمندی‌های رمز عبور:",
        passwordRequirements:
          "حداقل ۸ حرف، یک حرف بزرگ، یک عدد و یک حرف خاص (@$!%*?&).",
        step3Title: "معلومات مسلکی",
        step3Subtitle: "اختیاری — به فارغان دیگر کمک کنید تا شما را بشناسند.",
        jobTitleLabel: "عنوان شغلی فعلی",
        jobTitlePlaceholder: "مثلاً انجنیر ارشد نرم‌افزار",
        companyLabel: "شرکت فعلی",
        companyPlaceholder: "مثلاً Google",
        locationLabel: "موقعیت",
        locationPlaceholder: "مثلاً کابل، افغانستان",
        linkedinLabel: "پروفایل لینکدین",
        linkedinPlaceholder: "https://linkedin.com/in/…",
        profileImageLabel: "تصویر پروفایل",
        coverImageLabel: "تصویر پوش",
        bioLabel: "بیوگرافی",
        bioPlaceholder:
          "درباره مسیر، علایق و کاری که روی آن کار می‌کنید با فارغان دیگر بگویید…",
        submitHintReady:
          "پس از کلیک روی، از شما خواسته می‌شود هویت خود را با شماره تذکره تأیید کنید",
        submitHintReadyButton: "تکمیل ثبت‌نام",
        submitHintStart:
          "برای شروع روند تأیید، آی‌دی پوهنتون خود را در بالا جستجو کنید.",
        registering: "در حال ثبت‌نام…",
        completeRegistration: "تکمیل ثبت‌نام",
        alreadyHaveAccount: "از قبل حساب دارید؟",
        signInInstead: "به جای آن وارد شوید",
      },
      tazkira: {
        finalStep: "مرحله نهایی",
        title: "هویت خود را تأیید کنید",
        introBefore: "لطفاً",
        introBold: "شماره تذکره",
        introAfter:
          "خود را وارد کنید تا تأیید شود که شما همان محصلی هستید که در سوابق MIS یافتیم. این یک تأیید یک‌باره است.",
        label: "شماره تذکره",
        placeholder: "شماره تذکره خود را وارد کنید",
        cancel: "لغو",
        verifying: "در حال تأیید…",
        verifyAndRegister: "تأیید و ثبت‌نام",
      },
    },
  },

  ps: {
    auth: {
      brand: {
        network: "د KPU فارغانو شبکه",
        university: "د کابل پولیټخنیک پوهنتون",
      },
      login: {
        eyebrow: "خپل حساب ته ننوځئ",
        headingLine1: "د KPU ټولنې ته بېرته",
        headingHighlight: "ښه راغلاست.",
        intro:
          "له خپلو همټولګیو سره بېرته اړیکه ونیسئ، د دندو فرصتونه ومومئ او د کابل پولیټخنیک پوهنتون له ټولو پېښو خبر اوسئ.",
        cardBadge: "ننوتل",
        cardTitle: "ښه راغلاست",
        cardSubtitle: "خپل حساب ته د لاسرسي لپاره خپل معلومات داخل کړئ.",
        emailLabel: "د بریښنالیک پته",
        emailPlaceholder: "you@example.com",
        passwordLabel: "پټنوم",
        passwordPlaceholder: "خپل پټنوم داخل کړئ",
        rememberMe: "ما په یاد ولرئ",
        forgotPassword: "پټنوم مو هېر شوی؟",
        signIn: "ننوتل",
        signingIn: "ننوتل کیږي…",
        newToAlumni: "د KPU فارغانو ته نوي یاست؟",
        createVerified: "تایید شوی حساب جوړ کړئ",
        verifiedNote: "د MIS ریکارډونو له لارې تایید شوی · خوندي او محرم",
      },
      benefits: {
        resources: "د فارغانو ځانګړو سرچینو ته لاسرسی",
        network: "له ۱۰٬۰۰۰+ KPU فارغانو سره اړیکه",
        career: "د دندو فرصتونه او لارښوونه",
        events: "د فارغانو پېښې او راټولېدنې",
      },
      errors: {
        loginFailed: "ننوتل ناکام شو",
        loginFailedRetry: "ننوتل ناکام شو. مهرباني وکړئ بیا هڅه وکړئ.",
        universityIdRequired: "د پوهنتون آی‌ډي اړین دی",
        studentNotFound: "زده‌کوونکی ونه موندل شو. مهرباني وکړئ خپل د پوهنتون آی‌ډي وګورئ.",
        notGraduated: "تاسو لا تر اوسه نشئ کولی نوم‌لیکنه وکړئ — تاسو لا هم فعال محصل یاست او فارغ شوي نه یاست. نوم‌لیکنه یوازې تر فراغت وروسته ممکنه ده.",
        tazkiraRequired: "د تذکرې شمېره اړینه ده",
        tazkiraFailed:
          "د تذکرې تایید ناکام شو. مهرباني وکړئ خپل د تذکرې شمېره وګورئ.",
        universityIdNotFound:
          "د پوهنتون آی‌ډي زموږ په ریکارډونو کې ونه موندل شو. مهرباني وکړئ لومړی خپل د پوهنتون آی‌ډي وګورئ.",
        tazkiraNotFound:
          "د تذکرې شمېره زموږ په ریکارډونو کې ونه موندل شوه. مهرباني وکړئ خپل د تذکرې شمېره وګورئ.",
        mismatch:
          "د پوهنتون آی‌ډي او د تذکرې شمېره زموږ په ریکارډونو کې له یوه واحد زده‌کوونکي سره سمون نه خوري.",
        registrationFailed: "ثبت‌نام ناکام شو. مهرباني وکړئ بیا هڅه وکړئ.",
        searchProfileFirst: "مهرباني وکړئ لومړی خپل د زده‌کوونکي پروفایل ولټوئ",
      },
      register: {
        heroBadge: "تایید شوی ثبت‌نام",
        heroTitle: "خپل د KPU فارغ حساب جوړ کړئ",
        heroSubtitle:
          "د رسمي MIS ریکارډونو له لارې تایید شوی — خوندي، ځانګړی او د باور وړ.",
        stepFindProfile: "پروفایل ومومئ",
        stepAccount: "حساب",
        stepVerify: "تایید",
        verified: "تایید شوی",
        successTitle: "ثبت‌نام بریالی شو!",
        successBody:
          "د تایید شوي فارغانو شبکې ته ښه راغلاست. ستاسو پروفایل ته انتقالېږي…",
        failTitle: "ثبت‌نام ناکام شو",
        step1Title: "خپل د زده‌کوونکي پروفایل ومومئ",
        step1Subtitle:
          "زموږ د MIS ریکارډونو سره د تایید لپاره خپل د پوهنتون آی‌ډي داخل کړئ.",
        universityIdLabel: "د پوهنتون آی‌ډي",
        universityIdPlaceholder: "لکه KPU-2018-1234",
        searching: "لټون کیږي…",
        searchProfile: "پروفایل ولټوئ",
        profileFound: "پروفایل د MIS ریکارډونو کې وموندل شو",
        fieldFullName: "بشپړ نوم",
        fieldName: "نوم",
        fieldFatherName: "د پلار نوم",
        fieldGrandfatherName: "د نیکه نوم",
        fieldUniversityId: "د پوهنتون آی‌ډي",
        fieldFaculty: "پوهنځی",
        fieldDepartment: "ډیپارټمنټ",
        fieldGraduationYear: "د فراغت کال",
        fieldPhoneNumber: "د اړیکې شمېره",
        notAvailable: "نامعلوم",
        step2Title: "د حساب معلومات",
        step2Subtitle: "هغه معلومات وټاکئ چې د ننوتلو لپاره به یې کاروئ.",
        emailLabel: "د بریښنالیک پته",
        emailPlaceholder: "you@example.com",
        passwordLabel: "پټنوم",
        passwordPlaceholder: "یو قوي پټنوم وټاکئ",
        confirmPasswordLabel: "پټنوم تایید کړئ",
        confirmPasswordPlaceholder: "خپل پټنوم بیا داخل کړئ",
        strength: "قوت",
        strengthWeak: "ضعیف",
        strengthFair: "منځنی",
        strengthGood: "ښه",
        strengthStrong: "قوي",
        passwordRequirementsLabel: "د پټنوم اړتیاوې:",
        passwordRequirements:
          "لږ تر لږه ۸ توري، یو لوی توری، یو شمېره او یو ځانګړی توری (@$!%*?&).",
        step3Title: "مسلکي معلومات",
        step3Subtitle: "اختیاري — نورو فارغانو سره مرسته وکړئ چې تاسو وپېژني.",
        jobTitleLabel: "اوسنۍ دنده",
        jobTitlePlaceholder: "لکه ارشد سافټویر انجنیر",
        companyLabel: "اوسنۍ شرکت",
        companyPlaceholder: "لکه Google",
        locationLabel: "موقعیت",
        locationPlaceholder: "لکه کابل، افغانستان",
        linkedinLabel: "د لینکدین پروفایل",
        linkedinPlaceholder: "https://linkedin.com/in/…",
        profileImageLabel: "د پروفایل انځور",
        coverImageLabel: "د پوښ انځور",
        bioLabel: "پېژندنه",
        bioPlaceholder:
          "نورو فارغانو ته د خپل لار، علاقو او د هغه څه په اړه چې پرې کار کوئ ووایاست…",
        submitHintReady:
          "د کلیک کولو وروسته به له تاسو وغوښتل شي چې خپله پېژندنه د تذکرې شمېرې سره تایید کړئ",
        submitHintReadyButton: "ثبت‌نام بشپړ کړئ",
        submitHintStart:
          "د تایید بهیر پیلولو لپاره پورته خپل د پوهنتون آی‌ډي ولټوئ.",
        registering: "ثبتیږي…",
        completeRegistration: "ثبت‌نام بشپړ کړئ",
        alreadyHaveAccount: "دمخه حساب لرئ؟",
        signInInstead: "پر ځای یې ننوځئ",
      },
      tazkira: {
        finalStep: "وروستی پړاو",
        title: "خپله پېژندنه تایید کړئ",
        introBefore: "مهرباني وکړئ خپل",
        introBold: "د تذکرې شمېره",
        introAfter:
          "داخل کړئ ترڅو تایید شي چې تاسو هماغه زده‌کوونکی یاست چې موږ د MIS ریکارډونو کې وموندلو. دا یو ځل تایید دی.",
        label: "د تذکرې شمېره",
        placeholder: "خپل د تذکرې شمېره داخل کړئ",
        cancel: "لغوه",
        verifying: "تایید کیږي…",
        verifyAndRegister: "تایید او ثبت‌نام",
      },
    },
  },
};

export default auth;
