// Shared chrome: navigation, footer, user menu, notifications, common buttons.
const common = {
  en: {
    common: {
      brand: "KPU University",
      tagline: "Excellence in Education",
      login: "Login",
      logout: "Logout",
      profile: "Profile",
      account: "Account",
      manageProfile: "Manage profile",
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      close: "Close",
      search: "Search",
      submit: "Submit",
      apply: "Apply",
      back: "Back",
      viewAll: "View All",
      readMore: "Read More",
      seeMore: "See More",
      noResults: "No results found",
    },
    nav: {
      directory: "Directory",
      about: "About",
      contact: "Contact",
      career: "Career",
      mentorship: "Mentorship",
      events: "Events",
      giving: "Giving & Impact",
      home: "Home",
      dashboard: "Dashboard",
      alumniDirectory: "Alumni Directory",
      aboutKpu: "About KPU",
      contactUs: "Contact Us",
      careerOpportunities: "Career Opportunities",
      mentorshipHub: "Mentorship Hub",
      eventsCalendar: "Events Calendar",
    },
    notifications: {
      title: "Notifications",
      empty: "No notifications",
      reason: "Reason:",
    },
    userMenu: {
      signedInAs: "Signed in as",
      dashboard: "Dashboard",
      myProfile: "My Profile",
      myApplications: "My Applications",
      myEvents: "Registered Events",
      myMessages: "Messages",
      mentorship: "Mentorship",
      logout: "Logout",
    },
    footer: {
      about:
        "Fostering excellence, community, and lifelong learning for all Kabul Polytechnic University graduates.",
      quickLinks: "Quick Links",
      jobBoard: "Job Board",
      mentorshipProgram: "Mentorship Program",
      campusNews: "Campus News",
      university: "University",
      faculties: "Faculties",
      researchLabs: "Research Labs",
      contactOffice: "Contact Office",
      followUs: "Follow Us",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      eventGuidelines: "Event Guidelines",
      rights:
        "© 2023 Kabul Polytechnic University Alumni Association. All Rights Reserved.",
    },
  },

  da: {
    common: {
      brand: "پوهنتون پولیتخنیک کابل",
      tagline: "تعالی در آموزش",
      login: "ورود",
      logout: "خروج",
      profile: "پروفایل",
      account: "حساب",
      manageProfile: "مدیریت پروفایل",
      loading: "در حال بارگذاری...",
      save: "ذخیره",
      cancel: "لغو",
      delete: "حذف",
      edit: "ویرایش",
      close: "بستن",
      search: "جستجو",
      submit: "ثبت",
      apply: "درخواست",
      back: "بازگشت",
      viewAll: "مشاهده همه",
      readMore: "بیشتر بخوانید",
      seeMore: "بیشتر ببینید",
      noResults: "نتیجه‌ای یافت نشد",
    },
    nav: {
      directory: "دایرکتوری",
      about: "درباره ما",
      contact: "تماس",
      career: "کاریابی",
      mentorship: "رهنمایی",
      events: "رویدادها",
      giving: "کمک و تأثیر",
      home: "خانه",
      dashboard: "داشبورد",
      alumniDirectory: "دایرکتوری فارغان",
      aboutKpu: "درباره KPU",
      contactUs: "با ما در تماس شوید",
      careerOpportunities: "فرصت‌های شغلی",
      mentorshipHub: "مرکز رهنمایی",
      eventsCalendar: "تقویم رویدادها",
    },
    notifications: {
      title: "اطلاعیه‌ها",
      empty: "اطلاعیه‌ای نیست",
      reason: "دلیل:",
    },
    userMenu: {
      signedInAs: "وارد شده به نام",
      dashboard: "داشبورد",
      myProfile: "پروفایل من",
      myApplications: "درخواست‌های من",
      myEvents: "رویدادهای ثبت‌شده",
      myMessages: "پیام‌ها",
      mentorship: "رهنمایی",
      logout: "خروج",
    },
    footer: {
      about:
        "تقویت تعالی، همبستگی و آموزش مادام‌العمر برای تمام فارغان پوهنتون پولیتخنیک کابل.",
      quickLinks: "لینک‌های سریع",
      jobBoard: "تابلوی کاریابی",
      mentorshipProgram: "برنامه رهنمایی",
      campusNews: "اخبار پوهنتون",
      university: "پوهنتون",
      faculties: "پوهنځی‌ها",
      researchLabs: "آزمایشگاه‌های تحقیقاتی",
      contactOffice: "دفتر تماس",
      followUs: "ما را دنبال کنید",
      privacyPolicy: "سیاست حفظ حریم خصوصی",
      termsOfService: "شرایط استفاده",
      eventGuidelines: "رهنمود رویدادها",
      rights:
        "© ۲۰۲۳ انجمن فارغان پوهنتون پولیتخنیک کابل. تمام حقوق محفوظ است.",
    },
  },

  ps: {
    common: {
      brand: "د کابل پولیټخنیک پوهنتون",
      tagline: "په زده‌کړه کې عالي توب",
      login: "ننوتل",
      logout: "وتل",
      profile: "پروفایل",
      account: "حساب",
      manageProfile: "د پروفایل سمبالول",
      loading: "بارېدل...",
      save: "ثبت",
      cancel: "لغوه",
      delete: "ړنګول",
      edit: "سمول",
      close: "بندول",
      search: "لټون",
      submit: "ثبت",
      apply: "غوښتنه",
      back: "شاته",
      viewAll: "ټول وګورئ",
      readMore: "نور ولولئ",
      seeMore: "نور وګورئ",
      noResults: "هیڅ پایله ونه موندل شوه",
    },
    nav: {
      directory: "لارښود",
      about: "زموږ په اړه",
      contact: "اړیکه",
      career: "دندې",
      mentorship: "لارښوونه",
      events: "پیښې",
      giving: "مرسته او اغېز",
      home: "کور",
      dashboard: "ډشبورډ",
      alumniDirectory: "د فارغانو لارښود",
      aboutKpu: "د KPU په اړه",
      contactUs: "زموږ سره اړیکه",
      careerOpportunities: "د دندو فرصتونه",
      mentorshipHub: "د لارښوونې مرکز",
      eventsCalendar: "د پیښو جنتري",
    },
    notifications: {
      title: "خبرتیاوې",
      empty: "هیڅ خبرتیا نشته",
      reason: "دلیل:",
    },
    userMenu: {
      signedInAs: "ننوتلی په نوم",
      dashboard: "ډشبورډ",
      myProfile: "زما پروفایل",
      myApplications: "زما غوښتنلیکونه",
      myEvents: "ثبت‌شوې پیښې",
      myMessages: "پیغامونه",
      mentorship: "لارښوونه",
      logout: "وتل",
    },
    footer: {
      about:
        "د کابل پولیټخنیک پوهنتون د ټولو فارغانو لپاره د عالي توب، ټولنې او د عمر اوږدې زده‌کړې وده.",
      quickLinks: "چټک لینکونه",
      jobBoard: "د دندو بورد",
      mentorshipProgram: "د لارښوونې برنامه",
      campusNews: "د پوهنتون خبرونه",
      university: "پوهنتون",
      faculties: "پوهنځي",
      researchLabs: "د څېړنې لابراتوارونه",
      contactOffice: "د اړیکې دفتر",
      followUs: "موږ تعقیب کړئ",
      privacyPolicy: "د محرمیت تګلاره",
      termsOfService: "د کارونې شرایط",
      eventGuidelines: "د پیښو لارښود",
      rights:
        "© ۲۰۲۳ د کابل پولیټخنیک پوهنتون د فارغانو ټولنه. ټول حقوق خوندي دي.",
    },
  },
};

export default common;
