// ContactPage — namespace `contact`
const contact = {
  en: {
    contact: {
      alerts: {
        loginRequiredTitle: "Login Required",
        loginRequiredText: "Please login to send a message.",
        loginBtn: "Login",
        cancelBtn: "Cancel",
        validationTitle: "Validation Error",
        validationText: "Please enter your message.",
        sentTitle: "Message Sent!",
        sentText: "We will respond to you soon.",
        errorTitle: "Error",
        errorText: "Failed to send message. Please try again.",
      },
      cards: {
        emailTitle: "Email Us",
        emailCta: "Send Email",
        callTitle: "Call Us",
        callCta: "Call Now",
        visitTitle: "Visit Us",
        visitDetail: "KPU Campus, Kabul, Afghanistan",
        visitCta: "Get Directions",
        transcriptsTitle: "Transcripts",
        transcriptsCta: "Request",
      },
      quickLinks: {
        aboutTitle: "About Us",
        aboutDesc: "Our mission and history",
        eventsTitle: "Events",
        eventsDesc: "Upcoming alumni events",
        mentorshipTitle: "Mentorship",
        mentorshipDesc: "Join our program",
        jobsTitle: "Jobs",
        jobsDesc: "Career opportunities",
      },
      hero: {
        badge: "Get in Touch",
        title: "Contact Us",
        subtitle:
          "Reach out to the KPU Alumni Association — we're here to help.",
        campus: "KPU Campus, Kabul",
      },
      cardsSection: {
        label: "Reach Us",
        title: "Multiple Ways to Connect",
        subtitle: "Choose the channel that works best for you.",
      },
      form: {
        label: "Send a Message",
        title: "We'd Love to Hear From You",
        subtitle:
          "Questions about membership, events, or opportunities? Drop us a message.",
        firstName: "First Name",
        firstNamePlaceholder: "John",
        lastName: "Last Name",
        lastNamePlaceholder: "Doe",
        email: "Email",
        emailPlaceholder: "john.doe@example.com",
        subject: "Subject",
        subjectPlaceholder: "Enter subject...",
        message: "Message",
        messagePlaceholder: "Tell us how we can help you...",
        newsletter: "Subscribe to newsletter",
        sending: "Sending...",
        send: "Send Message",
        defaultSubject: "General Inquiry",
      },
      map: {
        title: "Kabul Polytechnic University",
        location: "Kabul, Afghanistan",
        mapAlt: "KPU Map",
        officeHours: "Office Hours",
        monThu: "Mon – Thu",
        monThuTime: "8:00 AM – 4:00 PM",
        friday: "Friday",
        fridayTime: "8:00 AM – 12:00 PM",
        weekend: "Sat – Sun",
        closed: "Closed",
        responseTime: "Response within 24–48 hours",
      },
      links: {
        label: "Explore More",
        title: "Quick Links",
        subtitle:
          "Useful shortcuts to help you navigate the alumni experience.",
      },
    },
  },

  da: {
    contact: {
      alerts: {
        loginRequiredTitle: "ورود لازم است",
        loginRequiredText: "برای ارسال پیام لطفاً وارد شوید.",
        loginBtn: "ورود",
        cancelBtn: "لغو",
        validationTitle: "خطای اعتبارسنجی",
        validationText: "لطفاً پیام خود را وارد کنید.",
        sentTitle: "پیام ارسال شد!",
        sentText: "به زودی به شما پاسخ خواهیم داد.",
        errorTitle: "خطا",
        errorText: "ارسال پیام ناکام شد. لطفاً دوباره تلاش کنید.",
      },
      cards: {
        emailTitle: "برای ما ایمیل بفرستید",
        emailCta: "ارسال ایمیل",
        callTitle: "با ما تماس بگیرید",
        callCta: "اکنون تماس بگیرید",
        visitTitle: "از ما دیدن کنید",
        visitDetail: "کمپس KPU، کابل، افغانستان",
        visitCta: "مسیریابی",
        transcriptsTitle: "ترانسکریپت‌ها",
        transcriptsCta: "درخواست",
      },
      quickLinks: {
        aboutTitle: "درباره ما",
        aboutDesc: "ماموریت و تاریخچه ما",
        eventsTitle: "رویدادها",
        eventsDesc: "رویدادهای پیش‌رو فارغان",
        mentorshipTitle: "رهنمایی",
        mentorshipDesc: "به برنامه ما بپیوندید",
        jobsTitle: "وظایف",
        jobsDesc: "فرصت‌های شغلی",
      },
      hero: {
        badge: "با ما در تماس شوید",
        title: "تماس با ما",
        subtitle:
          "با انجمن فارغان KPU در تماس شوید — ما برای کمک اینجا هستیم.",
        campus: "کمپس KPU، کابل",
      },
      cardsSection: {
        label: "با ما در ارتباط شوید",
        title: "راه‌های متعدد برای ارتباط",
        subtitle: "مجرایی را که برایتان بهترین است انتخاب کنید.",
      },
      form: {
        label: "ارسال پیام",
        title: "خوشحال می‌شویم از شما بشنویم",
        subtitle:
          "سوالاتی در مورد عضویت، رویدادها یا فرصت‌ها دارید؟ برای ما پیام بفرستید.",
        firstName: "نام",
        firstNamePlaceholder: "احمد",
        lastName: "تخلص",
        lastNamePlaceholder: "احمدی",
        email: "ایمیل",
        emailPlaceholder: "john.doe@example.com",
        subject: "موضوع",
        subjectPlaceholder: "موضوع را وارد کنید...",
        message: "پیام",
        messagePlaceholder: "به ما بگویید چگونه می‌توانیم کمک کنیم...",
        newsletter: "اشتراک در خبرنامه",
        sending: "در حال ارسال...",
        send: "ارسال پیام",
        defaultSubject: "پرسش عمومی",
      },
      map: {
        title: "پوهنتون پولیتخنیک کابل",
        location: "کابل، افغانستان",
        mapAlt: "نقشه KPU",
        officeHours: "ساعات کاری دفتر",
        monThu: "دوشنبه – پنجشنبه",
        monThuTime: "۸:۰۰ صبح – ۴:۰۰ بعد از ظهر",
        friday: "جمعه",
        fridayTime: "۸:۰۰ صبح – ۱۲:۰۰ ظهر",
        weekend: "شنبه – یکشنبه",
        closed: "بسته",
        responseTime: "پاسخ‌گویی در ظرف ۲۴ تا ۴۸ ساعت",
      },
      links: {
        label: "بیشتر کاوش کنید",
        title: "لینک‌های سریع",
        subtitle:
          "میانبرهای مفید برای کمک به شما در پیمایش تجربه فارغان.",
      },
    },
  },

  ps: {
    contact: {
      alerts: {
        loginRequiredTitle: "ننوتل اړین دي",
        loginRequiredText: "د پیغام لیږلو لپاره مهرباني وکړئ ننوځئ.",
        loginBtn: "ننوتل",
        cancelBtn: "لغوه",
        validationTitle: "د تاییدولو تېروتنه",
        validationText: "مهرباني وکړئ خپل پیغام ولیکئ.",
        sentTitle: "پیغام ولیږل شو!",
        sentText: "موږ به ژر تاسو ته ځواب درکړو.",
        errorTitle: "تېروتنه",
        errorText: "د پیغام لیږل ناکام شول. مهرباني وکړئ بیا هڅه وکړئ.",
      },
      cards: {
        emailTitle: "موږ ته ایمیل ولیږئ",
        emailCta: "ایمیل ولیږئ",
        callTitle: "موږ ته زنګ ووهئ",
        callCta: "اوس زنګ ووهئ",
        visitTitle: "موږ ته راشئ",
        visitDetail: "د KPU کمپس، کابل، افغانستان",
        visitCta: "لارښوونه ترلاسه کړئ",
        transcriptsTitle: "ترانسکریپټونه",
        transcriptsCta: "غوښتنه",
      },
      quickLinks: {
        aboutTitle: "زموږ په اړه",
        aboutDesc: "زموږ ماموریت او تاریخچه",
        eventsTitle: "پیښې",
        eventsDesc: "د فارغانو راتلونکې پیښې",
        mentorshipTitle: "لارښوونه",
        mentorshipDesc: "زموږ برنامې سره یوځای شئ",
        jobsTitle: "دندې",
        jobsDesc: "د دندو فرصتونه",
      },
      hero: {
        badge: "اړیکه ونیسئ",
        title: "زموږ سره اړیکه",
        subtitle:
          "د KPU د فارغانو ټولنې سره اړیکه ونیسئ — موږ د مرستې لپاره دلته یو.",
        campus: "د KPU کمپس، کابل",
      },
      cardsSection: {
        label: "موږ سره اړیکه",
        title: "د اړیکې ډېرې لارې",
        subtitle: "هغه لاره وټاکئ چې ستاسو لپاره ښه ده.",
      },
      form: {
        label: "پیغام ولیږئ",
        title: "موږ غواړو ستاسو خبرې واورو",
        subtitle:
          "د غړیتوب، پیښو یا فرصتونو په اړه پوښتنې لرئ؟ موږ ته پیغام ولیږئ.",
        firstName: "نوم",
        firstNamePlaceholder: "احمد",
        lastName: "تخلص",
        lastNamePlaceholder: "احمدي",
        email: "ایمیل",
        emailPlaceholder: "john.doe@example.com",
        subject: "موضوع",
        subjectPlaceholder: "موضوع ولیکئ...",
        message: "پیغام",
        messagePlaceholder: "موږ ته ووایاست چې څنګه مرسته وکړو...",
        newsletter: "خبرپاڼې کې ګډون وکړئ",
        sending: "لیږل کیږي...",
        send: "پیغام ولیږئ",
        defaultSubject: "عمومي پوښتنه",
      },
      map: {
        title: "د کابل پولیټخنیک پوهنتون",
        location: "کابل، افغانستان",
        mapAlt: "د KPU نقشه",
        officeHours: "د دفتر کاري ساعتونه",
        monThu: "دوشنبه – پنجشنبه",
        monThuTime: "۸:۰۰ سهار – ۴:۰۰ ماښام",
        friday: "جمعه",
        fridayTime: "۸:۰۰ سهار – ۱۲:۰۰ غرمه",
        weekend: "شنبه – یکشنبه",
        closed: "تړلی",
        responseTime: "په ۲۴ تر ۴۸ ساعتونو کې ځواب",
      },
      links: {
        label: "نور وپلټئ",
        title: "چټک لینکونه",
        subtitle:
          "ګټور لنډلارې چې د فارغانو تجربې کې ستاسو سره مرسته کوي.",
      },
    },
  },
};

export default contact;
