// User activity dashboard.
const dashboard = {
  en: {
    dashboard: {
      welcome: "Welcome back",
      subtitle: "Here is an overview of your alumni activity.",
      loading: "Loading your dashboard...",
      stats: {
        applications: "Job Applications",
        events: "Registered Events",
        mentorship: "Mentorship Requests",
        messages: "Messages",
        unread: "{{count}} unread",
        active: "Active",
        total: "Total",
      },
      completeness: {
        title: "Profile Completeness",
        subtitle: "A complete profile gets noticed more.",
        complete: "Your profile looks great!",
        action: "Complete profile",
      },
      quickActions: {
        title: "Quick Actions",
        findJobs: "Find Jobs",
        browseEvents: "Browse Events",
        findMentor: "Find a Mentor",
        editProfile: "Edit Profile",
        directory: "Alumni Directory",
        messages: "Messages",
      },
      recent: {
        applications: "Recent Applications",
        events: "Upcoming Events",
        messages: "Recent Messages",
        viewAll: "View all",
        emptyApplications: "You haven't applied to any jobs yet.",
        emptyEvents: "No upcoming registered events.",
        emptyMessages: "No messages yet.",
        appliedOn: "Applied on {{date}}",
        on: "On {{date}}",
      },
      status: {
        pending: "Pending",
        reviewed: "Reviewed",
        shortlisted: "Shortlisted",
        rejected: "Rejected",
        hired: "Hired",
        accepted: "Accepted",
        registered: "Registered",
        confirmed: "Confirmed",
      },
    },
  },

  da: {
    dashboard: {
      welcome: "خوش آمدید",
      subtitle: "این یک نمای کلی از فعالیت‌های شما در شبکه فارغان است.",
      loading: "در حال بارگذاری داشبورد شما...",
      stats: {
        applications: "درخواست‌های کاری",
        events: "رویدادهای ثبت‌شده",
        mentorship: "درخواست‌های رهنمایی",
        messages: "پیام‌ها",
        unread: "{{count}} خوانده‌نشده",
        active: "فعال",
        total: "مجموع",
      },
      completeness: {
        title: "تکمیل پروفایل",
        subtitle: "پروفایل کامل بیشتر دیده می‌شود.",
        complete: "پروفایل شما عالی است!",
        action: "تکمیل پروفایل",
      },
      quickActions: {
        title: "دسترسی سریع",
        findJobs: "یافتن کار",
        browseEvents: "مرور رویدادها",
        findMentor: "یافتن رهنما",
        editProfile: "ویرایش پروفایل",
        directory: "دایرکتوری فارغان",
        messages: "پیام‌ها",
      },
      recent: {
        applications: "درخواست‌های اخیر",
        events: "رویدادهای پیش‌رو",
        messages: "پیام‌های اخیر",
        viewAll: "مشاهده همه",
        emptyApplications: "هنوز برای هیچ کاری درخواست نداده‌اید.",
        emptyEvents: "رویداد ثبت‌شده پیش‌رویی وجود ندارد.",
        emptyMessages: "هنوز پیامی نیست.",
        appliedOn: "درخواست در تاریخ {{date}}",
        on: "در تاریخ {{date}}",
      },
      status: {
        pending: "در انتظار",
        reviewed: "بررسی‌شده",
        shortlisted: "فهرست کوتاه",
        rejected: "رد شده",
        hired: "استخدام‌شده",
        accepted: "پذیرفته‌شده",
        registered: "ثبت‌شده",
        confirmed: "تأییدشده",
      },
    },
  },

  ps: {
    dashboard: {
      welcome: "بیا هم ښه راغلاست",
      subtitle: "دلته ستاسو د فارغانو د فعالیتونو لنډه کتنه ده.",
      loading: "ستاسو ډشبورډ بارېږي...",
      stats: {
        applications: "د دندې غوښتنلیکونه",
        events: "ثبت‌شوې پیښې",
        mentorship: "د لارښوونې غوښتنې",
        messages: "پیغامونه",
        unread: "{{count}} نالوستل‌شوي",
        active: "فعال",
        total: "ټول",
      },
      completeness: {
        title: "د پروفایل بشپړتیا",
        subtitle: "بشپړ پروفایل ډېر په سترګو کېږي.",
        complete: "ستاسو پروفایل ښه ښکاري!",
        action: "پروفایل بشپړ کړئ",
      },
      quickActions: {
        title: "چټکې چارې",
        findJobs: "دندې ومومئ",
        browseEvents: "پیښې وګورئ",
        findMentor: "لارښوونکی ومومئ",
        editProfile: "پروفایل سمول",
        directory: "د فارغانو لارښود",
        messages: "پیغامونه",
      },
      recent: {
        applications: "وروستي غوښتنلیکونه",
        events: "راتلونکې پیښې",
        messages: "وروستي پیغامونه",
        viewAll: "ټول وګورئ",
        emptyApplications: "تاسو لا تر اوسه د هیڅ دندې غوښتنه نه ده کړې.",
        emptyEvents: "هیڅ راتلونکې ثبت‌شوې پیښه نشته.",
        emptyMessages: "تر اوسه هیڅ پیغام نشته.",
        appliedOn: "د {{date}} په نیټه غوښتنه شوې",
        on: "د {{date}} په نیټه",
      },
      status: {
        pending: "په تمه",
        reviewed: "کتل‌شوی",
        shortlisted: "لنډ‌لیست",
        rejected: "رد شوی",
        hired: "استخدام‌شوی",
        accepted: "منل‌شوی",
        registered: "ثبت‌شوی",
        confirmed: "تاییدشوی",
      },
    },
  },
};

export default dashboard;
