// DirectoryPage — namespace `directory`
const directory = {
  en: {
    directory: {
      loadError: "Failed to load alumni directory.",
      reload: "Retry",
      alumniNetwork: "Alumni Network",
      title: "Alumni Directory",
      subtitle: "Discover and connect with distinguished graduates shaping the world.",
      statAlumni: "Alumni",
      statFaculties: "Faculties",
      statGradYears: "Grad Years",
      somethingWrong: "Something went wrong",
      searchPlaceholder: "Search by name, company, or role...",
      allFaculties: "All Faculties",
      allYears: "All Years",
      resetFilters: "Reset filters",
      reset: "Reset",
      showingPrefix: "Showing",
      of: "of",
      alumniLower: "alumni",
      grid: "Grid",
      list: "List",
      noAlumniFound: "No alumni found",
      noAlumniHint: "Try different search terms or remove filters.",
      clearFilters: "Clear filters",
      viewProfile: "View Profile",
      joinDirectory: "Join Directory",
      classOf: "Class of {{year}}",
      view: "View",
      previous: "Previous",
      next: "Next",
    },
  },
  da: {
    directory: {
      loadError: "بارگذاری فهرست فارغ‌التحصیلان ناکام شد.",
      reload: "تلاش دوباره",
      alumniNetwork: "شبکه فارغ‌التحصیلان",
      title: "فهرست فارغ‌التحصیلان",
      subtitle: "فارغ‌التحصیلان برجسته‌ای را که جهان را شکل می‌دهند، بشناسید و با آنان ارتباط برقرار کنید.",
      statAlumni: "فارغ‌التحصیلان",
      statFaculties: "پوهنځی‌ها",
      statGradYears: "سال‌های فراغت",
      somethingWrong: "مشکلی پیش آمد",
      searchPlaceholder: "جستجو بر اساس نام، شرکت یا وظیفه...",
      allFaculties: "همه پوهنځی‌ها",
      allYears: "همه سال‌ها",
      resetFilters: "بازنشانی فیلترها",
      reset: "بازنشانی",
      showingPrefix: "نمایش",
      of: "از",
      alumniLower: "فارغ‌التحصیل",
      grid: "شبکه‌ای",
      list: "فهرستی",
      noAlumniFound: "هیچ فارغ‌التحصیلی یافت نشد",
      noAlumniHint: "عبارت جستجوی دیگری را امتحان کنید یا فیلترها را بردارید.",
      clearFilters: "پاک کردن فیلترها",
      viewProfile: "مشاهده پروفایل",
      joinDirectory: "پیوستن به فهرست",
      classOf: "دوره {{year}}",
      view: "مشاهده",
      previous: "قبلی",
      next: "بعدی",
    },
  },
  ps: {
    directory: {
      loadError: "د فارغانو لړلیک بار کول ناکام شول.",
      alumniNetwork: "د فارغانو شبکه",
      title: "د فارغانو لړلیک",
      subtitle: "هغه نوميالي فارغان وپېژنئ او ورسره اړیکه ونیسئ چې نړۍ بڼه ورکوي.",
      statAlumni: "فارغان",
      statFaculties: "پوهنځي",
      statGradYears: "د فراغت کالونه",
      somethingWrong: "یوه ستونزه رامنځته شوه",
      searchPlaceholder: "د نوم، شرکت یا دندې له مخې لټون...",
      allFaculties: "ټول پوهنځي",
      allYears: "ټول کالونه",
      resetFilters: "فلټرونه بیا تنظیمول",
      reset: "بیا تنظیم",
      showingPrefix: "ښودل کیږي",
      of: "له",
      alumniLower: "فارغان",
      grid: "جالۍ",
      list: "لړلیک",
      noAlumniFound: "هیڅ فارغ ونه موندل شو",
      noAlumniHint: "بل لټون عبارت وآزمویئ یا فلټرونه لرې کړئ.",
      clearFilters: "فلټرونه پاکول",
      viewProfile: "پروفایل کتل",
      joinDirectory: "لړلیک ته ګډون",
      classOf: "د {{year}} دوره",
      view: "کتل",
      previous: "مخکنی",
      next: "راتلونکی",
    },
  },
};

export default directory;
