// Events feature: list, detail, registered, verify-card, registration modal, card modal.
const events = {
  en: {
    events: {
      list: {
        heroAlt: "Events",
        featuredBadge: "Featured Event",
        noUpcomingBadge: "No Upcoming Events",
        noUpcomingTitle: "No upcoming events",
        noUpcomingTitleAccent: "at the moment",
        noUpcomingDesc: "We're not hosting anything new just yet. New reunions, workshops, and networking events are added regularly — check the calendar below or come back soon.",
        countdownLabel: "Event starts in:",
        years: "Years",
        months: "Months",
        days: "Days",
        hours: "Hours",
        mins: "Mins",
        secs: "Secs",
        online: "ONLINE",
        registrationDeadline: "Registration Deadline",
        eventDetails: "Event Details",
        premiumTitle: "Premium Event",
        premiumDesc: "Experience an unforgettable evening with distinguished alumni, faculty, and industry leaders.",
        attendees: "Attendees",
        speakers: "Speakers",
        awards: "Awards",
        stayTunedTitle: "Stay tuned",
        stayTunedDesc: "We're planning the next round of reunions, workshops, and networking sessions. Browse the calendar or past events below — you'll see new ones here as soon as they're published.",
        getNotified: "Get notified",
        searchPlaceholder: "Search events by title, type, or location…",
        filtersBtn: "Filters",
        filtersTitle: "Filters",
        filtersSubtitle: "Find events that fit you",
        stayUpdatedTitle: "Stay Updated",
        stayUpdatedDesc: "Get the latest event invitations in your inbox.",
        emailPlaceholder: "Email address",
        subscribe: "Subscribe",
        applyFilters: "Apply",
        loadingText: "Loading…",
        eventCalendar: "Event calendar",
        showingPrefix: "Showing",
        ofEvents: "events",
        listView: "List",
        calendarView: "Calendar",
        noEventsTitle: "No events found",
        noEventsDesc: "Try adjusting your search or removing some filters.",
        resetFilters: "Reset filters",
        viewEventDetails: "View Event Details",
        attendingCount: "{{n}} attending",
        spotsLeft: "{{n}} spots left",
        viewCard: "View Card",
        downloadCard: "Download Card",
        paginationRange: "Showing {{from}}–{{to}} of {{total}} events",
      },
      filter: {
        activeFilters: "{{n}} active filters",
        activeFilter: "{{n}} active filter",
        clearAll: "Clear all",
        viewTitle: "View",
        listView: "List View",
        calendar: "Calendar",
        categoriesTitle: "Categories",
        allEvents: "All Events",
        dateRange: "Date Range",
        from: "From",
        to: "To",
        clearDates: "Clear dates",
        resetAllFilters: "Reset All Filters",
      },
      calendar: {
        eventLegend: "Event",
        todayLegend: "Today",
        clickHint: "Click a day with events to filter the list view",
        moreEvents: "+{{n}} more",
      },
      button: {
        registerNow: "Register Now",
        registered: "Registered",
        registerAgain: "Register Again",
        registrationClosed: "Registration Closed",
      },
      alert: {
        errorTitle: "Error",
        loadEventsFailed: "Failed to load events",
        loginRequiredTitle: "Login Required",
        loginRequiredText: "Please login to register for this event",
        eventNotFoundTitle: "Event Not Found",
        eventNotFoundText: "The requested event could not be found.",
        alreadyRegisteredTitle: "Already Registered",
        alreadyRegisteredText: "You are already registered for this event.",
        gotIt: "Got it",
        eventCompletedTitle: "Event Completed",
        eventCompletedText: "This event has already happened and registration is no longer available.",
        seatsFullTitle: "Seats Full",
        seatsFullText: "You cannot register for this event because all the seats are full.",
        registrationSuccessTitle: "Registration Successful!",
        registrationSuccessText: "You have been registered for this event successfully.",
        great: "Great!",
        registrationClosedTitle: "Registration Closed",
        deadlinePassedHtml: "Deadline passed. Contact the KPU team <a href=\"/contact\" style=\"color: #2563eb; text-decoration: underline;\">if you want to participate</a>.",
        contactKpuTeam: "Contact KPU Team",
        close: "Close",
        registrationUnavailableTitle: "Registration Unavailable",
        registrationUnavailableText: "Registration is not available for this event.",
      },
      detail: {
        bgAlt: "Event Background",
        defaultImageAlt: "Event",
        notFoundTitle: "Event Not Found",
        backToEvents: "Back to Events",
        onlineEvent: "Online Event",
        offlineEvent: "Offline Event",
        defaultTitle: "Event Title",
        dateTbd: "Date TBD",
        timeTbd: "Time TBD",
        aboutTitle: "About This Event",
        locationTitle: "Location",
        joinMeeting: "Join Meeting →",
        requirementsTitle: "Requirements",
        registrationStatus: "Registration Status",
        registrationClosed: "Registration Closed",
        registrationOpen: "Registration Open",
        attendees: "Attendees",
        registrationFee: "Registration Fee",
        registrationDeadline: "Registration Deadline",
        confirmed: "Confirmed",
        registered: "Registered",
        viewCard: "View Card",
        downloadCard: "Download Card",
        cancelling: "Cancelling...",
        cancelRegistration: "Cancel Registration",
        cardDownloadedNote: "Card downloaded — cancellation disabled",
        registering: "Registering...",
        registerNow: "Register Now",
        deadlinePassedBox: "Registration deadline has passed",
        deadlinePassedNotePrefix: "Deadline passed. Contact the KPU team ",
        deadlinePassedNoteLink: "if you want to participate",
        deadlinePassedNoteSuffix: ".",
        loginToRegister: "Please login to register for this event",
        deadlinePassedNote: "The registration deadline for this event has passed.",
        organizerTitle: "Event Organizer",
        organizerName: "Name",
        organizerEmail: "Email",
        organizerPhone: "Phone",
        registerForEventTitle: "Register for Event",
        specialRequirementsLabel: "Special Requirements (Optional)",
        specialRequirementsPlaceholder: "Any special requirements or accommodations...",
        register: "Register",
        cancel: "Cancel",
        registerSuccessTitle: "Success!",
        registerSuccessText: "You have been registered for this event",
        registerErrorText: "Failed to register for event",
        cancelRegTitle: "Cancel Registration?",
        cancelRegText: "Are you sure you want to cancel your registration for this event?",
        cancelRegConfirm: "Yes, Cancel",
        cancelRegKeep: "No, Keep Registration",
        cancelledTitle: "Cancelled",
        cancelledText: "Your registration has been cancelled",
        cancelErrorText: "Failed to cancel registration",
        errorTitle: "Error",
        loadDetailsFailed: "Failed to load event details",
      },
      registered: {
        heroAlt: "Registered Events",
        heroTitle: "My Registered Events",
        heroSubtitle: "Manage and track all your event registrations in one place",
        loginRequiredTitle: "Login Required",
        loginRequiredText: "Please login to view your registered events.",
        login: "Login",
        emptyTitle: "No Registered Events",
        emptyText: "You haven't registered for any events yet.",
        browseEvents: "Browse Events",
        listTitle: "Your Registered Events ({{n}})",
        defaultEventAlt: "Event",
        eventTag: "EVENT",
        defaultTitle: "Event Title",
        timeNotAvailable: "Time not available",
        locationNotSpecified: "Location not specified",
        attendingCount: "{{n}} attending",
        viewDetails: "View Details",
        cancel: "Cancel",
        cancelTitle: "Cancel Registration",
        previous: "Previous",
        next: "Next",
        paginationRange: "Showing {{from}} to {{to}} of {{total}} events",
        cancelRegTitle: "Cancel Registration?",
        cancelRegText: "Are you sure you want to cancel your registration for this event?",
        cancelRegConfirm: "Yes, Cancel",
        cancelRegKeep: "Keep Registration",
        cancelledTitle: "Registration Cancelled",
        cancelledText: "Your registration has been cancelled successfully.",
        errorTitle: "Error",
        cancelFailed: "Failed to cancel registration",
        loadFailed: "Failed to load your registered events",
      },
      verify: {
        cardVerification: "KPU University — Card Verification",
        verificationFailed: "Verification Failed",
        couldNotVerify: "Could not verify this card.",
        cardVerified: "Card Verified",
        cardVerifiedDesc: "This participation card is authentic and valid.",
        invalidCard: "Invalid Card",
        invalidCardDesc: "No valid registration found for this event.",
        eventNotFound: "Event not found",
        participant: "Participant",
        id: "ID:",
        faculty: "Faculty",
        department: "Department",
        cardDownloaded: "Card Downloaded",
        unknown: "Unknown",
        verifiedFooter: "Verified by KPU Alumni System",
      },
      regModal: {
        title: "Register for Event",
        yourInformation: "Your Information",
        name: "Name:",
        faculty: "Faculty:",
        department: "Department:",
        graduationYear: "Graduation Year:",
        na: "N/A",
        eventDetails: "Event Details",
        date: "Date:",
        time: "Time:",
        location: "Location:",
        mode: "Mode:",
        online: "Online",
        inPerson: "In-Person",
        registrationFee: "Registration Fee:",
        emailLabel: "Email Address *",
        emailPlaceholder: "your.email@example.com",
        phoneLabel: "Phone Number *",
        phonePlaceholder: "+93 7XX XXX XXX",
        specialRequirementsLabel: "Special Requirements (Optional)",
        specialRequirementsPlaceholder: "Any special requirements, accommodations, or dietary restrictions...",
        registrationFailed: "Registration failed. Please try again later.",
        cancel: "Cancel",
        registering: "Registering...",
        submit: "Register for Event",
      },
      cardModal: {
        logoAlt: "KPU",
        errorTitle: "Error",
        cardNotReady: "Card not ready",
        downloadFailed: "Failed",
      },
    },
  },
  da: {
    events: {
      list: {
        heroAlt: "رویدادها",
        featuredBadge: "رویداد ویژه",
        noUpcomingBadge: "هیچ رویداد پیش‌رو نیست",
        noUpcomingTitle: "هیچ رویداد پیش‌رو وجود ندارد",
        noUpcomingTitleAccent: "در حال حاضر",
        noUpcomingDesc: "فعلاً برنامه جدیدی برگزار نمی‌کنیم. گردهمایی‌ها، ورکشاپ‌ها و رویدادهای شبکه‌سازی به‌طور منظم اضافه می‌شوند — تقویم زیر را ببینید یا به‌زودی دوباره سر بزنید.",
        countdownLabel: "رویداد آغاز می‌شود در:",
        years: "سال",
        months: "ماه",
        days: "روز",
        hours: "ساعت",
        mins: "دقیقه",
        secs: "ثانیه",
        online: "آنلاین",
        registrationDeadline: "مهلت ثبت‌نام",
        eventDetails: "جزئیات رویداد",
        premiumTitle: "رویداد ویژه",
        premiumDesc: "یک شب فراموش‌نشدنی را با فارغان برجسته، استادان و رهبران صنعت تجربه کنید.",
        attendees: "اشتراک‌کنندگان",
        speakers: "سخنرانان",
        awards: "جوایز",
        stayTunedTitle: "با ما همراه باشید",
        stayTunedDesc: "ما در حال برنامه‌ریزی دور بعدی گردهمایی‌ها، ورکشاپ‌ها و نشست‌های شبکه‌سازی هستیم. تقویم یا رویدادهای گذشته را در پایین ببینید — به‌محض نشر، رویدادهای جدید اینجا نمایان می‌شوند.",
        getNotified: "اطلاع‌رسانی برایم فعال شود",
        searchPlaceholder: "جستجوی رویدادها بر اساس عنوان، نوع یا موقعیت…",
        filtersBtn: "فیلترها",
        filtersTitle: "فیلترها",
        filtersSubtitle: "رویدادهای مناسب خود را پیدا کنید",
        stayUpdatedTitle: "به‌روز بمانید",
        stayUpdatedDesc: "آخرین دعوت‌نامه‌های رویداد را در ایمیل خود دریافت کنید.",
        emailPlaceholder: "آدرس ایمیل",
        subscribe: "اشتراک",
        applyFilters: "اعمال",
        loadingText: "در حال بارگیری…",
        eventCalendar: "تقویم رویدادها",
        showingPrefix: "نمایش",
        ofEvents: "رویداد",
        listView: "فهرست",
        calendarView: "تقویم",
        noEventsTitle: "هیچ رویدادی یافت نشد",
        noEventsDesc: "جستجوی خود را تنظیم کنید یا برخی فیلترها را حذف کنید.",
        resetFilters: "بازنشانی فیلترها",
        viewEventDetails: "مشاهده جزئیات رویداد",
        attendingCount: "{{n}} اشتراک‌کننده",
        spotsLeft: "{{n}} جای خالی",
        viewCard: "مشاهده کارت",
        downloadCard: "دانلود کارت",
        paginationRange: "نمایش {{from}}–{{to}} از {{total}} رویداد",
      },
      filter: {
        activeFilters: "{{n}} فیلتر فعال",
        activeFilter: "{{n}} فیلتر فعال",
        clearAll: "پاک کردن همه",
        viewTitle: "نمایش",
        listView: "نمای فهرستی",
        calendar: "تقویم",
        categoriesTitle: "دسته‌بندی‌ها",
        allEvents: "همه رویدادها",
        dateRange: "بازه زمانی",
        from: "از",
        to: "تا",
        clearDates: "پاک کردن تاریخ‌ها",
        resetAllFilters: "بازنشانی همه فیلترها",
      },
      calendar: {
        eventLegend: "رویداد",
        todayLegend: "امروز",
        clickHint: "برای فیلتر نمای فهرستی، روی روزی که رویداد دارد کلیک کنید",
        moreEvents: "+{{n}} مورد دیگر",
      },
      button: {
        registerNow: "اکنون ثبت‌نام کنید",
        registered: "ثبت‌نام شده",
        registerAgain: "دوباره ثبت‌نام کنید",
        registrationClosed: "ثبت‌نام بسته شد",
      },
      alert: {
        errorTitle: "خطا",
        loadEventsFailed: "بارگیری رویدادها ناکام شد",
        loginRequiredTitle: "ورود لازم است",
        loginRequiredText: "برای ثبت‌نام در این رویداد لطفاً وارد شوید",
        eventNotFoundTitle: "رویداد یافت نشد",
        eventNotFoundText: "رویداد مورد نظر یافت نشد.",
        alreadyRegisteredTitle: "قبلاً ثبت‌نام شده‌اید",
        alreadyRegisteredText: "شما قبلاً در این رویداد ثبت‌نام کرده‌اید.",
        gotIt: "فهمیدم",
        eventCompletedTitle: "رویداد به پایان رسید",
        eventCompletedText: "این رویداد قبلاً برگزار شده و ثبت‌نام دیگر در دسترس نیست.",
        seatsFullTitle: "ظرفیت تکمیل است",
        seatsFullText: "نمی‌توانید در این رویداد ثبت‌نام کنید زیرا تمام جای‌ها پر شده‌اند.",
        registrationSuccessTitle: "ثبت‌نام موفقانه!",
        registrationSuccessText: "شما با موفقیت در این رویداد ثبت‌نام شدید.",
        great: "عالی!",
        registrationClosedTitle: "ثبت‌نام بسته شد",
        deadlinePassedHtml: "مهلت گذشته است. با تیم پوهنتون پولی تخنیک تماس بگیرید <a href=\"/contact\" style=\"color: #2563eb; text-decoration: underline;\">اگر می‌خواهید اشتراک کنید</a>.",
        contactKpuTeam: "تماس با تیم پوهنتون",
        close: "بستن",
        registrationUnavailableTitle: "ثبت‌نام در دسترس نیست",
        registrationUnavailableText: "ثبت‌نام برای این رویداد در دسترس نیست.",
      },
      detail: {
        bgAlt: "پس‌زمینه رویداد",
        defaultImageAlt: "رویداد",
        notFoundTitle: "رویداد یافت نشد",
        backToEvents: "بازگشت به رویدادها",
        onlineEvent: "رویداد آنلاین",
        offlineEvent: "رویداد حضوری",
        defaultTitle: "عنوان رویداد",
        dateTbd: "تاریخ نامشخص",
        timeTbd: "زمان نامشخص",
        aboutTitle: "درباره این رویداد",
        locationTitle: "موقعیت",
        joinMeeting: "پیوستن به جلسه →",
        requirementsTitle: "نیازمندی‌ها",
        registrationStatus: "وضعیت ثبت‌نام",
        registrationClosed: "ثبت‌نام بسته شد",
        registrationOpen: "ثبت‌نام باز است",
        attendees: "اشتراک‌کنندگان",
        registrationFee: "هزینه ثبت‌نام",
        registrationDeadline: "مهلت ثبت‌نام",
        confirmed: "تأیید شده",
        registered: "ثبت‌نام شده",
        viewCard: "مشاهده کارت",
        downloadCard: "دانلود کارت",
        cancelling: "در حال لغو...",
        cancelRegistration: "لغو ثبت‌نام",
        cardDownloadedNote: "کارت دانلود شد — لغو غیرفعال است",
        registering: "در حال ثبت‌نام...",
        registerNow: "اکنون ثبت‌نام کنید",
        deadlinePassedBox: "مهلت ثبت‌نام گذشته است",
        deadlinePassedNotePrefix: "مهلت گذشته است. با تیم پوهنتون پولی تخنیک تماس بگیرید ",
        deadlinePassedNoteLink: "اگر می‌خواهید اشتراک کنید",
        deadlinePassedNoteSuffix: ".",
        loginToRegister: "برای ثبت‌نام در این رویداد لطفاً وارد شوید",
        deadlinePassedNote: "مهلت ثبت‌نام برای این رویداد گذشته است.",
        organizerTitle: "برگزارکننده رویداد",
        organizerName: "نام",
        organizerEmail: "ایمیل",
        organizerPhone: "شماره تماس",
        registerForEventTitle: "ثبت‌نام در رویداد",
        specialRequirementsLabel: "نیازمندی‌های ویژه (اختیاری)",
        specialRequirementsPlaceholder: "هرگونه نیازمندی یا تسهیلات ویژه...",
        register: "ثبت‌نام",
        cancel: "لغو",
        registerSuccessTitle: "موفقیت!",
        registerSuccessText: "شما در این رویداد ثبت‌نام شدید",
        registerErrorText: "ثبت‌نام در رویداد ناکام شد",
        cancelRegTitle: "لغو ثبت‌نام؟",
        cancelRegText: "آیا مطمئن هستید که می‌خواهید ثبت‌نام خود را در این رویداد لغو کنید؟",
        cancelRegConfirm: "بله، لغو شود",
        cancelRegKeep: "نه، ثبت‌نام حفظ شود",
        cancelledTitle: "لغو شد",
        cancelledText: "ثبت‌نام شما لغو شد",
        cancelErrorText: "لغو ثبت‌نام ناکام شد",
        errorTitle: "خطا",
        loadDetailsFailed: "بارگیری جزئیات رویداد ناکام شد",
      },
      registered: {
        heroAlt: "رویدادهای ثبت‌نام‌شده",
        heroTitle: "رویدادهای ثبت‌نام‌شده من",
        heroSubtitle: "تمام ثبت‌نام‌های رویداد خود را در یک جا مدیریت و پیگیری کنید",
        loginRequiredTitle: "ورود لازم است",
        loginRequiredText: "برای مشاهده رویدادهای ثبت‌نام‌شده خود لطفاً وارد شوید.",
        login: "ورود",
        emptyTitle: "هیچ رویداد ثبت‌نام‌شده‌ای نیست",
        emptyText: "شما هنوز در هیچ رویدادی ثبت‌نام نکرده‌اید.",
        browseEvents: "مرور رویدادها",
        listTitle: "رویدادهای ثبت‌نام‌شده شما ({{n}})",
        defaultEventAlt: "رویداد",
        eventTag: "رویداد",
        defaultTitle: "عنوان رویداد",
        timeNotAvailable: "زمان در دسترس نیست",
        locationNotSpecified: "موقعیت مشخص نشده",
        attendingCount: "{{n}} اشتراک‌کننده",
        viewDetails: "مشاهده جزئیات",
        cancel: "لغو",
        cancelTitle: "لغو ثبت‌نام",
        previous: "قبلی",
        next: "بعدی",
        paginationRange: "نمایش {{from}} تا {{to}} از {{total}} رویداد",
        cancelRegTitle: "لغو ثبت‌نام؟",
        cancelRegText: "آیا مطمئن هستید که می‌خواهید ثبت‌نام خود را در این رویداد لغو کنید؟",
        cancelRegConfirm: "بله، لغو شود",
        cancelRegKeep: "ثبت‌نام حفظ شود",
        cancelledTitle: "ثبت‌نام لغو شد",
        cancelledText: "ثبت‌نام شما با موفقیت لغو شد.",
        errorTitle: "خطا",
        cancelFailed: "لغو ثبت‌نام ناکام شد",
        loadFailed: "بارگیری رویدادهای ثبت‌نام‌شده شما ناکام شد",
      },
      verify: {
        cardVerification: "پوهنتون پولی تخنیک کابل — تأیید کارت",
        verificationFailed: "تأیید ناکام شد",
        couldNotVerify: "این کارت تأیید شده نتوانست.",
        cardVerified: "کارت تأیید شد",
        cardVerifiedDesc: "این کارت اشتراک معتبر و اصلی است.",
        invalidCard: "کارت نامعتبر",
        invalidCardDesc: "هیچ ثبت‌نام معتبری برای این رویداد یافت نشد.",
        eventNotFound: "رویداد یافت نشد",
        participant: "اشتراک‌کننده",
        id: "شناسه:",
        faculty: "پوهنځی",
        department: "دیپارتمنت",
        cardDownloaded: "کارت دانلود شد",
        unknown: "نامعلوم",
        verifiedFooter: "تأیید شده توسط سیستم فارغان پوهنتون پولی تخنیک",
      },
      regModal: {
        title: "ثبت‌نام در رویداد",
        yourInformation: "معلومات شما",
        name: "نام:",
        faculty: "پوهنځی:",
        department: "دیپارتمنت:",
        graduationYear: "سال فراغت:",
        na: "نامشخص",
        eventDetails: "جزئیات رویداد",
        date: "تاریخ:",
        time: "زمان:",
        location: "موقعیت:",
        mode: "حالت:",
        online: "آنلاین",
        inPerson: "حضوری",
        registrationFee: "هزینه ثبت‌نام:",
        emailLabel: "آدرس ایمیل *",
        emailPlaceholder: "your.email@example.com",
        phoneLabel: "شماره تماس *",
        phonePlaceholder: "+93 7XX XXX XXX",
        specialRequirementsLabel: "نیازمندی‌های ویژه (اختیاری)",
        specialRequirementsPlaceholder: "هرگونه نیازمندی، تسهیلات ویژه یا محدودیت غذایی...",
        registrationFailed: "ثبت‌نام ناکام شد. لطفاً بعداً دوباره تلاش کنید.",
        cancel: "لغو",
        registering: "در حال ثبت‌نام...",
        submit: "ثبت‌نام در رویداد",
      },
      cardModal: {
        logoAlt: "پوهنتون پولی تخنیک",
        errorTitle: "خطا",
        cardNotReady: "کارت آماده نیست",
        downloadFailed: "ناکام شد",
      },
    },
  },
  ps: {
    events: {
      list: {
        heroAlt: "پیښې",
        featuredBadge: "ځانګړې پیښه",
        noUpcomingBadge: "هیڅ راتلونکې پیښه نشته",
        noUpcomingTitle: "هیڅ راتلونکې پیښه نشته",
        noUpcomingTitleAccent: "اوس مهال",
        noUpcomingDesc: "موږ اوس مهال هیڅ نوې پروګرام نه ترسره کوو. د بیا یوځای کېدو غونډې، ورکشاپونه او د شبکه جوړونې پیښې په منظم ډول اضافه کیږي — لاندې جنتري وګورئ یا ژر بیا راشئ.",
        countdownLabel: "پیښه پیلیږي په:",
        years: "کاله",
        months: "میاشتې",
        days: "ورځې",
        hours: "ساعتونه",
        mins: "دقیقې",
        secs: "ثانیې",
        online: "آنلاین",
        registrationDeadline: "د نوم لیکنې وروستۍ نېټه",
        eventDetails: "د پیښې جزئیات",
        premiumTitle: "ځانګړې پیښه",
        premiumDesc: "د نومیالیو فارغانو، استادانو او د صنعت مشرانو سره یوه نه هېرېدونکې شپه تجربه کړئ.",
        attendees: "ګډونوال",
        speakers: "ویناوال",
        awards: "جایزې",
        stayTunedTitle: "موږ سره وساتئ",
        stayTunedDesc: "موږ د بیا یوځای کېدو غونډو، ورکشاپونو او د شبکه جوړونې ناستو راتلونکې پړاو پلانوو. لاندې جنتري یا تېرې پیښې وګورئ — څنګه چې خپرې شي، نوې پیښې به دلته ښکاره شي.",
        getNotified: "ما خبر کړئ",
        searchPlaceholder: "د پیښو لټون د سرلیک، ډول یا ځای له مخې…",
        filtersBtn: "فلټرونه",
        filtersTitle: "فلټرونه",
        filtersSubtitle: "خپلې مناسبې پیښې ومومئ",
        stayUpdatedTitle: "تازه پاتې شئ",
        stayUpdatedDesc: "د پیښو وروستي بلنلیکونه په خپل بریښنالیک کې ترلاسه کړئ.",
        emailPlaceholder: "د بریښنالیک پته",
        subscribe: "ګډون",
        applyFilters: "پلي کول",
        loadingText: "بارېږي…",
        eventCalendar: "د پیښو جنتري",
        showingPrefix: "ښودل کیږي",
        ofEvents: "پیښې",
        listView: "لیست",
        calendarView: "جنتري",
        noEventsTitle: "هیڅ پیښه ونه موندل شوه",
        noEventsDesc: "خپل لټون سم کړئ یا ځینې فلټرونه لرې کړئ.",
        resetFilters: "فلټرونه بیا تنظیمول",
        viewEventDetails: "د پیښې جزئیات وګورئ",
        attendingCount: "{{n}} ګډونوال",
        spotsLeft: "{{n}} خالي ځایونه",
        viewCard: "کارت وګورئ",
        downloadCard: "کارت ډاونلوډ کړئ",
        paginationRange: "ښودل کیږي {{from}}–{{to}} له {{total}} پیښو",
      },
      filter: {
        activeFilters: "{{n}} فعال فلټرونه",
        activeFilter: "{{n}} فعال فلټر",
        clearAll: "ټول پاک کړئ",
        viewTitle: "نمایش",
        listView: "د لیست نمایش",
        calendar: "جنتري",
        categoriesTitle: "کټګورۍ",
        allEvents: "ټولې پیښې",
        dateRange: "د نېټې حدود",
        from: "له",
        to: "تر",
        clearDates: "نېټې پاک کړئ",
        resetAllFilters: "ټول فلټرونه بیا تنظیمول",
      },
      calendar: {
        eventLegend: "پیښه",
        todayLegend: "نن",
        clickHint: "د لیست نمایش فلټر کولو لپاره په هغه ورځ کلیک وکړئ چې پیښه لري",
        moreEvents: "+{{n}} نور",
      },
      button: {
        registerNow: "اوس نوم ولیکئ",
        registered: "نوم لیکل شوی",
        registerAgain: "بیا نوم ولیکئ",
        registrationClosed: "نوم لیکنه بنده شوه",
      },
      alert: {
        errorTitle: "تېروتنه",
        loadEventsFailed: "د پیښو بارول ناکام شو",
        loginRequiredTitle: "ننوتل اړین دي",
        loginRequiredText: "په دې پیښه کې د نوم لیکنې لپاره مهرباني وکړئ ننوځئ",
        eventNotFoundTitle: "پیښه ونه موندل شوه",
        eventNotFoundText: "غوښتل شوې پیښه ونه موندل شوه.",
        alreadyRegisteredTitle: "مخکې نوم لیکل شوی",
        alreadyRegisteredText: "تاسو مخکې له مخکې په دې پیښه کې نوم لیکلی.",
        gotIt: "پوه شوم",
        eventCompletedTitle: "پیښه پای ته ورسېده",
        eventCompletedText: "دا پیښه دمخه ترسره شوې او نوم لیکنه نور شتون نلري.",
        seatsFullTitle: "ځایونه ډک دي",
        seatsFullText: "تاسو په دې پیښه کې نوم نشئ لیکلی ځکه چې ټول ځایونه ډک دي.",
        registrationSuccessTitle: "نوم لیکنه بریالۍ شوه!",
        registrationSuccessText: "تاسو په بریالیتوب سره په دې پیښه کې نوم لیکلی.",
        great: "ډېر ښه!",
        registrationClosedTitle: "نوم لیکنه بنده شوه",
        deadlinePassedHtml: "وروستۍ نېټه تېره شوه. د کابل پولي تخنیک ډلې سره اړیکه ونیسئ <a href=\"/contact\" style=\"color: #2563eb; text-decoration: underline;\">که غواړئ ګډون وکړئ</a>.",
        contactKpuTeam: "د پوهنتون ډلې سره اړیکه",
        close: "بندول",
        registrationUnavailableTitle: "نوم لیکنه شتون نلري",
        registrationUnavailableText: "د دې پیښې لپاره نوم لیکنه شتون نلري.",
      },
      detail: {
        bgAlt: "د پیښې شالید",
        defaultImageAlt: "پیښه",
        notFoundTitle: "پیښه ونه موندل شوه",
        backToEvents: "پیښو ته بیرته",
        onlineEvent: "آنلاین پیښه",
        offlineEvent: "حضوري پیښه",
        defaultTitle: "د پیښې سرلیک",
        dateTbd: "نېټه نامعلومه",
        timeTbd: "وخت نامعلوم",
        aboutTitle: "د دې پیښې په اړه",
        locationTitle: "ځای",
        joinMeeting: "ناستې ته ورګډ شئ →",
        requirementsTitle: "اړتیاوې",
        registrationStatus: "د نوم لیکنې حالت",
        registrationClosed: "نوم لیکنه بنده شوه",
        registrationOpen: "نوم لیکنه پرانیستې ده",
        attendees: "ګډونوال",
        registrationFee: "د نوم لیکنې فیس",
        registrationDeadline: "د نوم لیکنې وروستۍ نېټه",
        confirmed: "تایید شوی",
        registered: "نوم لیکل شوی",
        viewCard: "کارت وګورئ",
        downloadCard: "کارت ډاونلوډ کړئ",
        cancelling: "لغوه کیږي...",
        cancelRegistration: "نوم لیکنه لغوه کړئ",
        cardDownloadedNote: "کارت ډاونلوډ شو — لغوه کول غیرفعال دي",
        registering: "نوم لیکل کیږي...",
        registerNow: "اوس نوم ولیکئ",
        deadlinePassedBox: "د نوم لیکنې وروستۍ نېټه تېره شوه",
        deadlinePassedNotePrefix: "وروستۍ نېټه تېره شوه. د کابل پولي تخنیک ډلې سره اړیکه ونیسئ ",
        deadlinePassedNoteLink: "که غواړئ ګډون وکړئ",
        deadlinePassedNoteSuffix: ".",
        loginToRegister: "په دې پیښه کې د نوم لیکنې لپاره مهرباني وکړئ ننوځئ",
        deadlinePassedNote: "د دې پیښې د نوم لیکنې وروستۍ نېټه تېره شوه.",
        organizerTitle: "د پیښې مدیر",
        organizerName: "نوم",
        organizerEmail: "بریښنالیک",
        organizerPhone: "تلیفون",
        registerForEventTitle: "د پیښې لپاره نوم لیکنه",
        specialRequirementsLabel: "ځانګړې اړتیاوې (اختیاري)",
        specialRequirementsPlaceholder: "هره ځانګړې اړتیا یا اسانتیا...",
        register: "نوم لیکنه",
        cancel: "لغوه",
        registerSuccessTitle: "بریا!",
        registerSuccessText: "تاسو په دې پیښه کې نوم لیکلی",
        registerErrorText: "په پیښه کې نوم لیکنه ناکامه شوه",
        cancelRegTitle: "نوم لیکنه لغوه کړئ؟",
        cancelRegText: "ایا تاسو ډاډه یاست چې غواړئ په دې پیښه کې خپله نوم لیکنه لغوه کړئ؟",
        cancelRegConfirm: "هو، لغوه یې کړئ",
        cancelRegKeep: "نه، نوم لیکنه وساتئ",
        cancelledTitle: "لغوه شو",
        cancelledText: "ستاسو نوم لیکنه لغوه شوه",
        cancelErrorText: "د نوم لیکنې لغوه کول ناکام شو",
        errorTitle: "تېروتنه",
        loadDetailsFailed: "د پیښې جزئیاتو بارول ناکام شو",
      },
      registered: {
        heroAlt: "ثبت شوې پیښې",
        heroTitle: "زما ثبت شوې پیښې",
        heroSubtitle: "د خپلو ټولو پیښو نوم لیکنې په یوه ځای کې اداره او تعقیب کړئ",
        loginRequiredTitle: "ننوتل اړین دي",
        loginRequiredText: "د خپلو ثبت شویو پیښو لیدلو لپاره مهرباني وکړئ ننوځئ.",
        login: "ننوتل",
        emptyTitle: "هیڅ ثبت شوې پیښه نشته",
        emptyText: "تاسو لا تر اوسه په هیڅ پیښه کې نوم نه دی لیکلی.",
        browseEvents: "پیښې وګورئ",
        listTitle: "ستاسو ثبت شوې پیښې ({{n}})",
        defaultEventAlt: "پیښه",
        eventTag: "پیښه",
        defaultTitle: "د پیښې سرلیک",
        timeNotAvailable: "وخت شتون نلري",
        locationNotSpecified: "ځای نه دی مشخص شوی",
        attendingCount: "{{n}} ګډونوال",
        viewDetails: "جزئیات وګورئ",
        cancel: "لغوه",
        cancelTitle: "نوم لیکنه لغوه کړئ",
        previous: "مخکینی",
        next: "راتلونکی",
        paginationRange: "ښودل کیږي {{from}} تر {{to}} له {{total}} پیښو",
        cancelRegTitle: "نوم لیکنه لغوه کړئ؟",
        cancelRegText: "ایا تاسو ډاډه یاست چې غواړئ په دې پیښه کې خپله نوم لیکنه لغوه کړئ؟",
        cancelRegConfirm: "هو، لغوه یې کړئ",
        cancelRegKeep: "نوم لیکنه وساتئ",
        cancelledTitle: "نوم لیکنه لغوه شوه",
        cancelledText: "ستاسو نوم لیکنه په بریالیتوب سره لغوه شوه.",
        errorTitle: "تېروتنه",
        cancelFailed: "د نوم لیکنې لغوه کول ناکام شو",
        loadFailed: "ستاسو د ثبت شویو پیښو بارول ناکام شو",
      },
      verify: {
        cardVerification: "د کابل پولي تخنیک پوهنتون — د کارت تصدیق",
        verificationFailed: "تصدیق ناکام شو",
        couldNotVerify: "دا کارت تصدیق نشو.",
        cardVerified: "کارت تصدیق شو",
        cardVerifiedDesc: "دا د ګډون کارت اصلي او معتبر دی.",
        invalidCard: "نامعتبر کارت",
        invalidCardDesc: "د دې پیښې لپاره هیڅ معتبره نوم لیکنه ونه موندل شوه.",
        eventNotFound: "پیښه ونه موندل شوه",
        participant: "ګډونوال",
        id: "پیژندنه:",
        faculty: "پوهنځی",
        department: "څانګه",
        cardDownloaded: "کارت ډاونلوډ شو",
        unknown: "نامعلوم",
        verifiedFooter: "د کابل پولي تخنیک د فارغانو سیسټم لخوا تصدیق شوی",
      },
      regModal: {
        title: "د پیښې لپاره نوم لیکنه",
        yourInformation: "ستاسو معلومات",
        name: "نوم:",
        faculty: "پوهنځی:",
        department: "څانګه:",
        graduationYear: "د فراغت کال:",
        na: "نامعلوم",
        eventDetails: "د پیښې جزئیات",
        date: "نېټه:",
        time: "وخت:",
        location: "ځای:",
        mode: "حالت:",
        online: "آنلاین",
        inPerson: "حضوري",
        registrationFee: "د نوم لیکنې فیس:",
        emailLabel: "د بریښنالیک پته *",
        emailPlaceholder: "your.email@example.com",
        phoneLabel: "د تلیفون شمیره *",
        phonePlaceholder: "+93 7XX XXX XXX",
        specialRequirementsLabel: "ځانګړې اړتیاوې (اختیاري)",
        specialRequirementsPlaceholder: "هره ځانګړې اړتیا، اسانتیا یا د خوراک محدودیت...",
        registrationFailed: "نوم لیکنه ناکامه شوه. مهرباني وکړئ وروسته بیا هڅه وکړئ.",
        cancel: "لغوه",
        registering: "نوم لیکل کیږي...",
        submit: "د پیښې لپاره نوم لیکنه",
      },
      cardModal: {
        logoAlt: "کابل پولي تخنیک",
        errorTitle: "تېروتنه",
        cardNotReady: "کارت چمتو نه دی",
        downloadFailed: "ناکام شو",
      },
    },
  },
};

export default events;
