// Localization module for JOB-related pages/components.
// Shape: { en: { jobs: {...} }, da: { jobs: {...} }, ps: { jobs: {...} } }
// Covers: JobBoard.jsx, JobDetailsPage.jsx, ApplicationsPage.jsx, ApplyModal.jsx

const jobs = {
  en: {
    jobs: {
      board: {
        badge: 'KPU Alumni Job Board',
        heroTitle: 'Find Your Next Opportunity',
        heroSubtitle: 'Discover careers posted by fellow alumni and trusted employers.',
        searchPlaceholder: 'Job title, company, or keywords...',
        locationPlaceholder: 'Location...',
        filters: 'Filters',
        filtersSubtitle: 'Narrow down your search',
        activeFilter_one: '{{count}} active filter',
        activeFilter_other: '{{count}} active filters',
        clearAll: 'Clear all',
        jobType: 'Job Type',
        industry: 'Industry',
        experienceLevel: 'Experience Level',
        fullTime: 'Full-time',
        contract: 'Contract',
        remote: 'Remote',
        construction: 'Construction',
        softwareEngineering: 'Software Engineering',
        energy: 'Energy',
        allLevels: 'All Levels',
        entryLevel: 'Entry Level',
        intermediate: 'Intermediate',
        seniorLevel: 'Senior Level',
        directorLead: 'Director / Lead',
        resetAllFilters: 'Reset All Filters',
        resetFilters: 'Reset filters',
        alumnus: 'Alumnus',
        recently: 'Recently',
        applied: 'Applied',
        applyNow: 'Apply Now',
        apply: 'Apply',
        details: 'Details',
        loading: 'Loading…',
        showingCount: 'Showing {{shown}} of {{total}} jobs',
        showingTotal: 'Showing {{total}} jobs',
        list: 'List',
        grid: 'Grid',
        noJobsTitle: 'No jobs found',
        noJobsText: 'Try adjusting your search or removing some filters.',
        perPage: 'Per page:',
        alreadyAppliedTitle: 'Already Applied',
        alreadyAppliedText: 'You have already applied for this job.',
        successTitle: 'Application Submitted!',
        successText: 'Your job application has been submitted successfully.',
        successConfirm: 'Great!',
      },
      details: {
        notFoundHero: 'Job Not Found',
        notAvailableTitle: 'Job Not Available',
        notAvailableText: "The job you're looking for doesn't exist or has been removed.",
        notFoundError: 'Job not found',
        loadError: 'Failed to load job details',
        backToJobs: 'Back to Jobs',
        myApplications: 'My Applications',
        opportunityBadge: 'Job Opportunity',
        alumnus: 'Alumnus',
        postedOn: 'Posted {{date}}',
        applied: 'Applied',
        alreadyApplied: 'Already Applied',
        applyNow: 'Apply Now',
        applyForThisJob: 'Apply for This Job',
        browseSimilar: 'Browse Similar Jobs',
        jobDescription: 'Job Description',
        noDescription: 'No description provided.',
        requirements: 'Requirements',
        benefits: 'Benefits',
        jobInformation: 'Job Information',
        actions: 'Actions',
        infoExperienceLevel: 'Experience Level',
        infoIndustry: 'Industry',
        infoJobType: 'Job Type',
        infoLocation: 'Location',
        infoSalary: 'Salary',
        infoApplyBy: 'Apply by',
        postedByAlumnus: 'Posted by KPU Alumnus',
        loginRequiredTitle: 'Login Required',
        loginRequiredText: 'Please login to apply for this job.',
        loginConfirm: 'Login',
        loginCancel: 'Cancel',
        successTitle: 'Application Submitted!',
        successText: 'Your job application has been submitted successfully.',
        successConfirm: 'Great!',
      },
      applications: {
        heroTitle: 'My Job Applications',
        heroSubtitle: 'Track and manage all your job applications in one place',
        backToProfile: 'Back to Profile',
        emptyTitle: 'No Job Applications Yet',
        emptyText: "You haven't applied to any jobs yet. Start browsing and apply to your dream jobs!",
        browseJobs: 'Browse Jobs',
        defaultJobTitle: 'Job Title',
        defaultCompany: 'Company',
        statusPending: 'pending',
        seeMore: 'See More',
        removeTitle: 'Remove application',
        showingTotal: 'Showing {{total}} applications',
        show: 'Show:',
        all: 'All',
        confirmRemoveTitle: 'Remove Application?',
        confirmRemoveHtml: 'Are you sure you want to remove your application for <strong>{{title}}</strong>?',
        confirmRemoveYes: 'Yes, remove it',
        confirmRemoveCancel: 'Cancel',
        removedTitle: 'Application Removed',
        removedText: 'Your job application has been removed successfully.',
        errorTitle: 'Error',
        removeError: 'Failed to remove application. Please try again.',
      },
      apply: {
        title: 'Apply for Position',
        yourInformation: 'Your Information',
        name: 'Name',
        faculty: 'Faculty',
        department: 'Department',
        graduation: 'Graduation',
        notAvailable: 'N/A',
        email: 'Email',
        emailPlaceholder: 'your.email@example.com',
        phone: 'Phone',
        phonePlaceholder: '+93 7XX XXX XXX',
        coverLetter: 'Cover Letter',
        optional: '(optional)',
        coverLetterPlaceholder: "Tell us why you're a great fit...",
        cvResume: 'CV / Resume',
        dropzoneTitle: 'Click to upload or drag and drop',
        dropzoneHint: 'PDF, DOC, DOCX · max 5MB',
        removeFile: 'Remove file',
        uploading: 'Uploading… {{percent}}%',
        uploadComplete: 'Upload complete',
        processing: 'Processing...',
        replaceFile: 'Replace file',
        cancel: 'Cancel',
        submitting: 'Submitting...',
        uploadingShort: 'Uploading {{percent}}%',
        submit: 'Submit Application',
        invalidType: 'Please upload a PDF or Word document',
        tooLarge: 'File size must be less than 5MB',
        submitError: 'Failed to submit application',
        alreadyAppliedTitle: 'Already Applied',
        errorTitle: 'Error',
      },
    },
  },
  da: {
    jobs: {
      board: {
        badge: 'تابلوی کاریابی فارغان پولیتخنیک کابل',
        heroTitle: 'فرصت شغلی بعدی خود را بیابید',
        heroSubtitle: 'مشاغل ارائه‌شده توسط فارغان همدوره و کارفرمایان معتبر را کشف کنید.',
        searchPlaceholder: 'عنوان وظیفه، شرکت یا کلمات کلیدی...',
        locationPlaceholder: 'موقعیت...',
        filters: 'فلترها',
        filtersSubtitle: 'جستجوی خود را محدود کنید',
        activeFilter_one: '{{count}} فلتر فعال',
        activeFilter_other: '{{count}} فلتر فعال',
        clearAll: 'پاک کردن همه',
        jobType: 'نوع وظیفه',
        industry: 'صنعت',
        experienceLevel: 'سطح تجربه',
        fullTime: 'تمام‌وقت',
        contract: 'قراردادی',
        remote: 'از راه دور',
        construction: 'ساختمانی',
        softwareEngineering: 'انجنیری نرم‌افزار',
        energy: 'انرژی',
        allLevels: 'همه سطوح',
        entryLevel: 'سطح مقدماتی',
        intermediate: 'متوسط',
        seniorLevel: 'سطح ارشد',
        directorLead: 'مدیر / سرپرست',
        resetAllFilters: 'بازنشانی همه فلترها',
        resetFilters: 'بازنشانی فلترها',
        alumnus: 'فارغ‌التحصیل',
        recently: 'اخیراً',
        applied: 'درخواست داده شد',
        applyNow: 'همین حالا درخواست دهید',
        apply: 'درخواست',
        details: 'جزئیات',
        loading: 'در حال بارگذاری…',
        showingCount: 'نمایش {{shown}} از {{total}} وظیفه',
        showingTotal: 'نمایش {{total}} وظیفه',
        list: 'فهرست',
        grid: 'جدولی',
        noJobsTitle: 'هیچ وظیفه‌ای یافت نشد',
        noJobsText: 'جستجوی خود را تنظیم کنید یا برخی فلترها را حذف کنید.',
        perPage: 'در هر صفحه:',
        alreadyAppliedTitle: 'قبلاً درخواست داده‌اید',
        alreadyAppliedText: 'شما قبلاً برای این وظیفه درخواست داده‌اید.',
        successTitle: 'درخواست ارسال شد!',
        successText: 'درخواست شغلی شما با موفقیت ارسال شد.',
        successConfirm: 'عالی!',
      },
      details: {
        notFoundHero: 'وظیفه یافت نشد',
        notAvailableTitle: 'وظیفه در دسترس نیست',
        notAvailableText: 'وظیفه‌ای که به دنبال آن هستید وجود ندارد یا حذف شده است.',
        notFoundError: 'وظیفه یافت نشد',
        loadError: 'بارگذاری جزئیات وظیفه ناکام شد',
        backToJobs: 'بازگشت به وظایف',
        myApplications: 'درخواست‌های من',
        opportunityBadge: 'فرصت شغلی',
        alumnus: 'فارغ‌التحصیل',
        postedOn: 'تاریخ نشر {{date}}',
        applied: 'درخواست داده شد',
        alreadyApplied: 'قبلاً درخواست داده شد',
        applyNow: 'همین حالا درخواست دهید',
        applyForThisJob: 'برای این وظیفه درخواست دهید',
        browseSimilar: 'مشاهده وظایف مشابه',
        jobDescription: 'شرح وظیفه',
        noDescription: 'هیچ شرحی ارائه نشده است.',
        requirements: 'الزامات',
        benefits: 'مزایا',
        jobInformation: 'معلومات وظیفه',
        actions: 'اقدامات',
        infoExperienceLevel: 'سطح تجربه',
        infoIndustry: 'صنعت',
        infoJobType: 'نوع وظیفه',
        infoLocation: 'موقعیت',
        infoSalary: 'معاش',
        infoApplyBy: 'مهلت درخواست تا',
        postedByAlumnus: 'نشر شده توسط فارغ‌التحصیل پولیتخنیک کابل',
        loginRequiredTitle: 'ورود لازم است',
        loginRequiredText: 'برای درخواست این وظیفه لطفاً وارد شوید.',
        loginConfirm: 'ورود',
        loginCancel: 'لغو',
        successTitle: 'درخواست ارسال شد!',
        successText: 'درخواست شغلی شما با موفقیت ارسال شد.',
        successConfirm: 'عالی!',
      },
      applications: {
        heroTitle: 'درخواست‌های شغلی من',
        heroSubtitle: 'تمام درخواست‌های شغلی خود را در یک جا پیگیری و مدیریت کنید',
        backToProfile: 'بازگشت به پروفایل',
        emptyTitle: 'هنوز هیچ درخواست شغلی ندارید',
        emptyText: 'شما هنوز برای هیچ وظیفه‌ای درخواست نداده‌اید. جستجو را شروع کنید و برای وظایف مورد علاقه خود درخواست دهید!',
        browseJobs: 'مشاهده وظایف',
        defaultJobTitle: 'عنوان وظیفه',
        defaultCompany: 'شرکت',
        statusPending: 'در انتظار',
        seeMore: 'بیشتر ببینید',
        removeTitle: 'حذف درخواست',
        showingTotal: 'نمایش {{total}} درخواست',
        show: 'نمایش:',
        all: 'همه',
        confirmRemoveTitle: 'درخواست حذف شود؟',
        confirmRemoveHtml: 'آیا مطمئن هستید که می‌خواهید درخواست خود را برای <strong>{{title}}</strong> حذف کنید؟',
        confirmRemoveYes: 'بله، حذف شود',
        confirmRemoveCancel: 'لغو',
        removedTitle: 'درخواست حذف شد',
        removedText: 'درخواست شغلی شما با موفقیت حذف شد.',
        errorTitle: 'خطا',
        removeError: 'حذف درخواست ناکام شد. لطفاً دوباره تلاش کنید.',
      },
      apply: {
        title: 'درخواست برای وظیفه',
        yourInformation: 'معلومات شما',
        name: 'نام',
        faculty: 'پوهنځی',
        department: 'دیپارتمنت',
        graduation: 'سال فراغت',
        notAvailable: 'موجود نیست',
        email: 'ایمیل',
        emailPlaceholder: 'your.email@example.com',
        phone: 'شماره تماس',
        phonePlaceholder: '+93 7XX XXX XXX',
        coverLetter: 'مکتوب پوششی',
        optional: '(اختیاری)',
        coverLetterPlaceholder: 'برای ما بنویسید چرا گزینه مناسبی هستید...',
        cvResume: 'سی‌وی / خلص سوانح',
        dropzoneTitle: 'برای بارگذاری کلیک کنید یا فایل را بکشید و رها کنید',
        dropzoneHint: 'PDF، DOC، DOCX · حداکثر ۵ مگابایت',
        removeFile: 'حذف فایل',
        uploading: 'در حال بارگذاری… {{percent}}٪',
        uploadComplete: 'بارگذاری تکمیل شد',
        processing: 'در حال پردازش...',
        replaceFile: 'تعویض فایل',
        cancel: 'لغو',
        submitting: 'در حال ارسال...',
        uploadingShort: 'در حال بارگذاری {{percent}}٪',
        submit: 'ارسال درخواست',
        invalidType: 'لطفاً یک فایل PDF یا Word بارگذاری کنید',
        tooLarge: 'حجم فایل باید کمتر از ۵ مگابایت باشد',
        submitError: 'ارسال درخواست ناکام شد',
        alreadyAppliedTitle: 'قبلاً درخواست داده‌اید',
        errorTitle: 'خطا',
      },
    },
  },
  ps: {
    jobs: {
      board: {
        badge: 'د کابل پولیتخنیک د فارغانو د کار تخته',
        heroTitle: 'خپله راتلونکې فرصت ومومئ',
        heroSubtitle: 'هغه دندې وپلټئ چې د همدورې فارغانو او باوري کارفرمایانو لخوا اعلان شوي.',
        searchPlaceholder: 'د دندې نوم، شرکت یا کلیدي کلمې...',
        locationPlaceholder: 'موقعیت...',
        filters: 'فلټرونه',
        filtersSubtitle: 'خپله پلټنه محدوده کړئ',
        activeFilter_one: '{{count}} فعال فلټر',
        activeFilter_other: '{{count}} فعال فلټرونه',
        clearAll: 'ټول پاک کړئ',
        jobType: 'د دندې ډول',
        industry: 'صنعت',
        experienceLevel: 'د تجربې کچه',
        fullTime: 'بشپړ وخت',
        contract: 'قراردادي',
        remote: 'له لرې',
        construction: 'ساختماني',
        softwareEngineering: 'د سافټویر انجنیري',
        energy: 'انرژي',
        allLevels: 'ټولې کچې',
        entryLevel: 'لومړنۍ کچه',
        intermediate: 'منځنۍ',
        seniorLevel: 'لوړه کچه',
        directorLead: 'مدیر / مشر',
        resetAllFilters: 'ټول فلټرونه بیا تنظیم کړئ',
        resetFilters: 'فلټرونه بیا تنظیم کړئ',
        alumnus: 'فارغ',
        recently: 'پدې وروستیو کې',
        applied: 'غوښتنلیک وسپارل شو',
        applyNow: 'اوس غوښتنه وکړئ',
        apply: 'غوښتنه',
        details: 'جزئیات',
        loading: 'په بارولو کې…',
        showingCount: 'د {{total}} دندو څخه {{shown}} ښودل کیږي',
        showingTotal: '{{total}} دندې ښودل کیږي',
        list: 'لیست',
        grid: 'جدول',
        noJobsTitle: 'هیڅ دنده ونه موندل شوه',
        noJobsText: 'خپله پلټنه سمه کړئ یا ځینې فلټرونه لرې کړئ.',
        perPage: 'په هره پاڼه کې:',
        alreadyAppliedTitle: 'مخکې غوښتنه شوې',
        alreadyAppliedText: 'تاسو مخکې له مخکې د دې دندې لپاره غوښتنه کړې ده.',
        successTitle: 'غوښتنلیک وسپارل شو!',
        successText: 'ستاسو د دندې غوښتنلیک په بریالیتوب سره وسپارل شو.',
        successConfirm: 'عالي!',
      },
      details: {
        notFoundHero: 'دنده ونه موندل شوه',
        notAvailableTitle: 'دنده شتون نلري',
        notAvailableText: 'هغه دنده چې تاسو یې لټوئ شتون نلري یا لرې شوې ده.',
        notFoundError: 'دنده ونه موندل شوه',
        loadError: 'د دندې جزئیات بارول ناکام شول',
        backToJobs: 'بیرته دندو ته',
        myApplications: 'زما غوښتنلیکونه',
        opportunityBadge: 'د کار فرصت',
        alumnus: 'فارغ',
        postedOn: 'د خپرولو نیټه {{date}}',
        applied: 'غوښتنلیک وسپارل شو',
        alreadyApplied: 'مخکې غوښتنه شوې',
        applyNow: 'اوس غوښتنه وکړئ',
        applyForThisJob: 'د دې دندې لپاره غوښتنه وکړئ',
        browseSimilar: 'ورته دندې وګورئ',
        jobDescription: 'د دندې تشریح',
        noDescription: 'هیڅ تشریح نه ده ورکړل شوې.',
        requirements: 'اړتیاوې',
        benefits: 'ګټې',
        jobInformation: 'د دندې معلومات',
        actions: 'اقدامات',
        infoExperienceLevel: 'د تجربې کچه',
        infoIndustry: 'صنعت',
        infoJobType: 'د دندې ډول',
        infoLocation: 'موقعیت',
        infoSalary: 'معاش',
        infoApplyBy: 'د غوښتنې وروستۍ نیټه',
        postedByAlumnus: 'د کابل پولیتخنیک د فارغ لخوا خپور شوی',
        loginRequiredTitle: 'ننوتل اړین دي',
        loginRequiredText: 'د دې دندې لپاره د غوښتنې لپاره مهرباني وکړئ ننوځئ.',
        loginConfirm: 'ننوتل',
        loginCancel: 'لغوه',
        successTitle: 'غوښتنلیک وسپارل شو!',
        successText: 'ستاسو د دندې غوښتنلیک په بریالیتوب سره وسپارل شو.',
        successConfirm: 'عالي!',
      },
      applications: {
        heroTitle: 'زما د دندو غوښتنلیکونه',
        heroSubtitle: 'خپل ټول د دندو غوښتنلیکونه په یوه ځای کې تعقیب او اداره کړئ',
        backToProfile: 'بیرته پروفایل ته',
        emptyTitle: 'تر اوسه د دندې هیڅ غوښتنلیک نشته',
        emptyText: 'تاسو تر اوسه د هیڅ دندې لپاره غوښتنه نه ده کړې. پلټنه پیل کړئ او د خپلو خوښې دندو لپاره غوښتنه وکړئ!',
        browseJobs: 'دندې وګورئ',
        defaultJobTitle: 'د دندې نوم',
        defaultCompany: 'شرکت',
        statusPending: 'په تمه',
        seeMore: 'نور وګورئ',
        removeTitle: 'غوښتنلیک لرې کړئ',
        showingTotal: '{{total}} غوښتنلیکونه ښودل کیږي',
        show: 'ښودل:',
        all: 'ټول',
        confirmRemoveTitle: 'غوښتنلیک لرې شي؟',
        confirmRemoveHtml: 'ایا تاسو ډاډه یاست چې غواړئ خپل غوښتنلیک د <strong>{{title}}</strong> لپاره لرې کړئ؟',
        confirmRemoveYes: 'هو، لرې یې کړئ',
        confirmRemoveCancel: 'لغوه',
        removedTitle: 'غوښتنلیک لرې شو',
        removedText: 'ستاسو د دندې غوښتنلیک په بریالیتوب سره لرې شو.',
        errorTitle: 'تېروتنه',
        removeError: 'د غوښتنلیک لرې کول ناکام شول. مهرباني وکړئ بیا هڅه وکړئ.',
      },
      apply: {
        title: 'د دندې لپاره غوښتنه',
        yourInformation: 'ستاسو معلومات',
        name: 'نوم',
        faculty: 'پوهنځی',
        department: 'څانګه',
        graduation: 'د فراغت کال',
        notAvailable: 'شتون نلري',
        email: 'بریښنالیک',
        emailPlaceholder: 'your.email@example.com',
        phone: 'د اړیکې شمیره',
        phonePlaceholder: '+93 7XX XXX XXX',
        coverLetter: 'پوښښ لیک',
        optional: '(اختیاري)',
        coverLetterPlaceholder: 'موږ ته ولیکئ چې ولې تاسو مناسب انتخاب یاست...',
        cvResume: 'سي وي / لنډ سوانح',
        dropzoneTitle: 'د بارولو لپاره کلیک وکړئ یا فایل راکش او پریږدئ',
        dropzoneHint: 'PDF، DOC، DOCX · تر ۵ میګابایټ پورې',
        removeFile: 'فایل لرې کړئ',
        uploading: 'په بارولو کې… {{percent}}٪',
        uploadComplete: 'بارول بشپړ شول',
        processing: 'په پروسس کې...',
        replaceFile: 'فایل بدل کړئ',
        cancel: 'لغوه',
        submitting: 'په سپارلو کې...',
        uploadingShort: 'په بارولو کې {{percent}}٪',
        submit: 'غوښتنلیک وسپارئ',
        invalidType: 'مهرباني وکړئ د PDF یا Word سند بار کړئ',
        tooLarge: 'د فایل اندازه باید له ۵ میګابایټ څخه کمه وي',
        submitError: 'د غوښتنلیک سپارل ناکام شول',
        alreadyAppliedTitle: 'مخکې غوښتنه شوې',
        errorTitle: 'تېروتنه',
      },
    },
  },
};

export default jobs;
