// LegalPage (Giving / Donations page) — namespace `legal`
const legal = {
  en: {
    legal: {
      modal: {
        donateToProject: "Donate to Project",
        quickGift: "Quick Gift",
        supportKpu: "Support KPU",
        prefilled: "Pre-filled from your profile — you can edit any field.",
        fullName: "Full Name *",
        fullNamePlaceholder: "Your full name",
        email: "Email *",
        emailPlaceholder: "you@example.com",
        phone: "Phone",
        phoneOptional: "(optional)",
        phonePlaceholder: "+93 700 000 000",
        graduationYear: "Graduation Year",
        graduationYearPlaceholder: "e.g. 2015",
        amount: "Amount (USD) *",
        amountPlaceholder: "100",
        yourMessage: "Your Message",
        messageOptional: "(optional — may be displayed publicly)",
        messagePlaceholder: "Share why you're donating or a message of support…",
        cancel: "Cancel",
        submitDonation: "Submit Donation",
        errNameRequired: "Name is required",
        errEmailRequired: "Email is required",
        errEmailInvalid: "Invalid email address",
        errPhoneInvalid: "Invalid phone number",
        errAmountInvalid: "Please enter a valid amount",
        thankYouTitle: "Thank You!",
        thankYouText:
          "Your donation pledge has been submitted. Our team will contact you shortly to process the donation.",
        errorTitle: "Error",
        donateFailed: "Failed to submit donation.",
      },
      hero: {
        badge: "KPU Giving",
        title: "Invest in the Next Generation of Engineers",
        subtitle:
          "Your gift funds scholarships, modern labs and research opportunities for KPU students — and shapes the future of Afghanistan's technical leadership.",
        exploreProjects: "Explore Projects",
        donateNow: "Donate Now",
      },
      metrics: {
        totalRaised: "Total Raised",
        generousDonors: "Generous Donors",
        activeProjects: "Active Projects",
        overallProgress: "Overall Progress",
      },
      projects: {
        eyebrow: "Active Initiatives",
        title: "Fundraising Projects",
        subtitle:
          "Join us in supporting these important initiatives that will benefit current and future KPU students.",
        emptyTitle: "No active fundraising projects right now",
        emptySubtitle: "Check back later or make a quick donation below",
        funded: "{{pct}}% FUNDED",
        donorOne: "{{count}} donor",
        donorOther: "{{count}} donors",
        raised: "Raised",
        goal: "Goal:",
        remaining: "Remaining",
        donateToThis: "Donate to this Project",
      },
      quickGift: {
        eyebrow: "Quick Gift",
        title: "Every contribution counts",
        subtitle:
          "No project, no paperwork — just a direct gift to support KPU students. Choose an amount or enter your own.",
        chooseAmount: "Choose an amount",
        customAmount: "Or enter a custom amount",
        customPlaceholder: "Enter amount in USD",
        processDonation: "Process Donation",
        privacyNote:
          "Your information is private. Our team will contact you to complete the gift.",
        selectAmountTitle: "Please select an amount",
      },
      wall: {
        eyebrow: "Wall of Honor",
        title: "Our Generous Donors",
        subtitle:
          "We gratefully acknowledge the alumni and supporters who have made contributions to KPU.",
        emptyTitle: "No completed donations yet",
        emptySubtitle: "Be the first to contribute!",
        classOf: "Class of {{year}}",
        projects: "Projects",
        quickGift: "Quick Gift",
        seeAll: "See All {{count}} Donors",
        rankBadge: "Rank #{{rank}}",
      },
    },
  },

  da: {
    legal: {
      modal: {
        donateToProject: "کمک به پروژه",
        quickGift: "کمک سریع",
        supportKpu: "حمایت از KPU",
        prefilled: "از پروفایل شما تکمیل شده — می‌توانید هر فیلد را ویرایش کنید.",
        fullName: "نام کامل *",
        fullNamePlaceholder: "نام کامل شما",
        email: "ایمیل *",
        emailPlaceholder: "you@example.com",
        phone: "تلیفون",
        phoneOptional: "(اختیاری)",
        phonePlaceholder: "+93 700 000 000",
        graduationYear: "سال فراغت",
        graduationYearPlaceholder: "مثلاً ۲۰۱۵",
        amount: "مبلغ (دالر) *",
        amountPlaceholder: "۱۰۰",
        yourMessage: "پیام شما",
        messageOptional: "(اختیاری — ممکن است به صورت عمومی نمایش داده شود)",
        messagePlaceholder: "بنویسید چرا کمک می‌کنید یا یک پیام حمایتی…",
        cancel: "لغو",
        submitDonation: "ثبت کمک",
        errNameRequired: "نام الزامی است",
        errEmailRequired: "ایمیل الزامی است",
        errEmailInvalid: "آدرس ایمیل نامعتبر است",
        errPhoneInvalid: "شماره تلیفون نامعتبر است",
        errAmountInvalid: "لطفاً یک مبلغ معتبر وارد کنید",
        thankYouTitle: "تشکر از شما!",
        thankYouText:
          "تعهد کمک شما ثبت شد. تیم ما به زودی برای پردازش کمک با شما تماس خواهد گرفت.",
        errorTitle: "خطا",
        donateFailed: "ثبت کمک ناکام شد.",
      },
      hero: {
        badge: "کمک‌های KPU",
        title: "روی نسل بعدی انجینران سرمایه‌گذاری کنید",
        subtitle:
          "کمک شما بورسیه‌ها، آزمایشگاه‌های مدرن و فرصت‌های تحقیقاتی را برای دانشجویان KPU تأمین می‌کند — و آینده رهبری تخنیکی افغانستان را شکل می‌دهد.",
        exploreProjects: "کاوش پروژه‌ها",
        donateNow: "اکنون کمک کنید",
      },
      metrics: {
        totalRaised: "مجموع جمع‌آوری شده",
        generousDonors: "اهداکنندگان سخاوتمند",
        activeProjects: "پروژه‌های فعال",
        overallProgress: "پیشرفت کلی",
      },
      projects: {
        eyebrow: "ابتکارات فعال",
        title: "پروژه‌های جمع‌آوری کمک",
        subtitle:
          "در حمایت از این ابتکارات مهم که به نفع دانشجویان فعلی و آینده KPU است با ما همراه شوید.",
        emptyTitle: "در حال حاضر هیچ پروژه فعال جمع‌آوری کمک وجود ندارد",
        emptySubtitle: "بعداً سر بزنید یا در پایین یک کمک سریع انجام دهید",
        funded: "٪{{pct}} تأمین شده",
        donorOne: "{{count}} اهداکننده",
        donorOther: "{{count}} اهداکننده",
        raised: "جمع‌آوری شده",
        goal: "هدف:",
        remaining: "باقی‌مانده",
        donateToThis: "به این پروژه کمک کنید",
      },
      quickGift: {
        eyebrow: "کمک سریع",
        title: "هر کمک اهمیت دارد",
        subtitle:
          "بدون پروژه، بدون کاغذبازی — فقط یک کمک مستقیم برای حمایت از دانشجویان KPU. یک مبلغ انتخاب کنید یا مبلغ خود را وارد کنید.",
        chooseAmount: "یک مبلغ انتخاب کنید",
        customAmount: "یا یک مبلغ دلخواه وارد کنید",
        customPlaceholder: "مبلغ را به دالر وارد کنید",
        processDonation: "پردازش کمک",
        privacyNote:
          "معلومات شما محرم است. تیم ما برای تکمیل کمک با شما تماس خواهد گرفت.",
        selectAmountTitle: "لطفاً یک مبلغ انتخاب کنید",
      },
      wall: {
        eyebrow: "دیوار افتخار",
        title: "اهداکنندگان سخاوتمند ما",
        subtitle:
          "ما با سپاسگزاری از فارغان و حامیانی که به KPU کمک کرده‌اند قدردانی می‌کنیم.",
        emptyTitle: "هنوز هیچ کمک تکمیل‌شده‌ای وجود ندارد",
        emptySubtitle: "اولین کمک‌کننده باشید!",
        classOf: "فارغ سال {{year}}",
        projects: "پروژه‌ها",
        quickGift: "کمک سریع",
        seeAll: "مشاهده تمام {{count}} اهداکننده",
        rankBadge: "رتبه #{{rank}}",
      },
    },
  },

  ps: {
    legal: {
      modal: {
        donateToProject: "پروژې ته مرسته",
        quickGift: "چټکه ډالۍ",
        supportKpu: "د KPU ملاتړ",
        prefilled: "ستاسو له پروفایل څخه ډک شوی — تاسو کولی شئ هره برخه سمه کړئ.",
        fullName: "بشپړ نوم *",
        fullNamePlaceholder: "ستاسو بشپړ نوم",
        email: "ایمیل *",
        emailPlaceholder: "you@example.com",
        phone: "تلیفون",
        phoneOptional: "(اختیاري)",
        phonePlaceholder: "+93 700 000 000",
        graduationYear: "د فراغت کال",
        graduationYearPlaceholder: "لکه ۲۰۱۵",
        amount: "اندازه (ډالر) *",
        amountPlaceholder: "۱۰۰",
        yourMessage: "ستاسو پیغام",
        messageOptional: "(اختیاري — کېدای شي په عامه توګه وښودل شي)",
        messagePlaceholder: "ولیکئ چې ولې مرسته کوئ یا د ملاتړ یو پیغام…",
        cancel: "لغوه",
        submitDonation: "مرسته ثبت کړئ",
        errNameRequired: "نوم اړین دی",
        errEmailRequired: "ایمیل اړین دی",
        errEmailInvalid: "ناسم ایمیل پته",
        errPhoneInvalid: "ناسم تلیفون شمیره",
        errAmountInvalid: "مهرباني وکړئ سمه اندازه ولیکئ",
        thankYouTitle: "مننه!",
        thankYouText:
          "ستاسو د مرستې ژمنه ثبت شوه. زموږ ټیم به ژر تاسو سره د مرستې د پروسس لپاره اړیکه ونیسي.",
        errorTitle: "تېروتنه",
        donateFailed: "د مرستې ثبتول ناکام شول.",
      },
      hero: {
        badge: "د KPU مرستې",
        title: "د انجنیرانو په راتلونکي نسل کې پانګونه وکړئ",
        subtitle:
          "ستاسو ډالۍ د KPU زده‌کوونکو لپاره بورسونه، عصري لابراتوارونه او د څېړنې فرصتونه تمویلوي — او د افغانستان د تخنیکي مشرتابه راتلونکی جوړوي.",
        exploreProjects: "پروژې وپلټئ",
        donateNow: "اوس مرسته وکړئ",
      },
      metrics: {
        totalRaised: "ټوله راټوله شوې",
        generousDonors: "سخي مرسته‌کوونکي",
        activeProjects: "فعالې پروژې",
        overallProgress: "ټوله پرمختیا",
      },
      projects: {
        eyebrow: "فعالې نوښتونه",
        title: "د مرستو راټولولو پروژې",
        subtitle:
          "د دې مهمو نوښتونو په ملاتړ کې زموږ سره یوځای شئ چې د KPU اوسنیو او راتلونکو زده‌کوونکو ته ګټه رسوي.",
        emptyTitle: "اوس مهال د مرستو راټولولو فعاله پروژه نشته",
        emptySubtitle: "وروسته بیا وګورئ یا لاندې یوه چټکه مرسته وکړئ",
        funded: "{{pct}}٪ تمویل شوې",
        donorOne: "{{count}} مرسته‌کوونکی",
        donorOther: "{{count}} مرسته‌کوونکي",
        raised: "راټوله شوې",
        goal: "موخه:",
        remaining: "پاتې",
        donateToThis: "دې پروژې ته مرسته وکړئ",
      },
      quickGift: {
        eyebrow: "چټکه ډالۍ",
        title: "هره مرسته ارزښت لري",
        subtitle:
          "نه پروژه، نه کاغذپاڼې — یوازې یوه مستقیمه ډالۍ د KPU زده‌کوونکو ملاتړ لپاره. یوه اندازه وټاکئ یا خپله اندازه ولیکئ.",
        chooseAmount: "یوه اندازه وټاکئ",
        customAmount: "یا یوه دلخواه اندازه ولیکئ",
        customPlaceholder: "اندازه په ډالرو ولیکئ",
        processDonation: "مرسته پروسس کړئ",
        privacyNote:
          "ستاسو معلومات محرم دي. زموږ ټیم به د ډالۍ د بشپړولو لپاره تاسو سره اړیکه ونیسي.",
        selectAmountTitle: "مهرباني وکړئ یوه اندازه وټاکئ",
      },
      wall: {
        eyebrow: "د ویاړ دیوال",
        title: "زموږ سخي مرسته‌کوونکي",
        subtitle:
          "موږ په منندوینه سره د هغو فارغانو او ملاتړو ستاینه کوو چې KPU سره یې مرسته کړې.",
        emptyTitle: "تر اوسه هیڅ بشپړه مرسته نشته",
        emptySubtitle: "لومړی مرسته‌کوونکی اوسئ!",
        classOf: "د {{year}} کال فارغ",
        projects: "پروژې",
        quickGift: "چټکه ډالۍ",
        seeAll: "ټول {{count}} مرسته‌کوونکي وګورئ",
        rankBadge: "درجه #{{rank}}",
      },
    },
  },
};

export default legal;
