/**
 * Media Center translations (en / da / ps).
 * Auto-discovered by src/localization/i18n.js.
 */
const media = {
  en: {
    nav: { media: 'Media Center' },
    media: {
      title: 'Media Center',
      subtitle: 'Photos, videos, documents and news shared with KPU alumni',
      searchPlaceholder: 'Search by title, tag or keyword…',
      filters: 'Filters',
      clearFilters: 'Clear filters',
      allCategories: 'All categories',
      allTypes: 'All types',
      allMedia: 'All Media',
      images: 'Images',
      videos: 'Videos',
      documents: 'Documents',
      mediaType: 'Media Type',
      categories: 'Categories',
      dateRange: 'Date Range',
      from: 'From',
      to: 'To',
      currentSelection: 'Current Selection',
      clearAll: 'Clear All',
      allDepartments: 'All departments',
      featuredOnly: 'Featured only',
      sort: 'Sort',
      sortNewest: 'Latest first',
      sortOldest: 'Oldest first',
      sortMostViewed: 'Most viewed',
      sortMostDownloaded: 'Most downloaded',
      viewGrid: 'Grid',
      viewList: 'List',
      viewCard: 'Cards',
      noResultsTitle: 'No media found',
      noResultsDesc: 'Try adjusting your search or filters.',
      errorLoading: 'Failed to load media. Please try again.',
      loadMore: 'Load more',
      results: '{{count}} items',
      by: 'By',
      views: 'views',
      downloads: 'downloads',
      featured: 'Featured',
      view: 'View',
      detail: {
        back: 'Back to Media Center',
        download: 'Download',
        downloading: 'Downloading…',
        share: 'Share',
        copied: 'Link copied to clipboard',
        preview: 'Preview',
        noPreview: 'Preview is not available for this file type. Use the download button.',
        attachments: 'Attachments',
        related: 'Related media',
        published: 'Published',
        department: 'Department',
        author: 'Author',
        category: 'Category',
        type: 'Type',
        loadFailed: 'Failed to load this media item.',
        downloadFailed: 'Download failed. Please try again.',
      },
    },
  },
  da: {
    nav: { media: 'مرکز رسانه‌ها' },
    media: {
      title: 'مرکز رسانه‌ها',
      subtitle: 'عکس‌ها، ویدیوها، اسناد و اخبار به اشتراک‌گذاشته‌شده با فارغ‌التحصیلان',
      searchPlaceholder: 'جستجو بر اساس عنوان، برچسب یا کلیدواژه…',
      filters: 'فیلترها',
      clearFilters: 'پاک کردن فیلترها',
      allCategories: 'همه دسته‌ها',
      allTypes: 'همه انواع',
      allMedia: 'همه رسانه‌ها',
      images: 'تصاویر',
      videos: 'ویدیوها',
      documents: 'اسناد',
      mediaType: 'نوع رسانه',
      categories: 'دسته‌ها',
      dateRange: 'بازه زمانی',
      from: 'از',
      to: 'تا',
      currentSelection: 'انتخاب فعلی',
      clearAll: 'پاک کردن همه',
      allDepartments: 'همه دیپارتمنت‌ها',
      featuredOnly: 'فقط ویژه',
      sort: 'مرتب‌سازی',
      sortNewest: 'جدیدترین',
      sortOldest: 'قدیمی‌ترین',
      sortMostViewed: 'پربازدیدترین',
      sortMostDownloaded: 'پردانلودترین',
      viewGrid: 'شبکه‌ای',
      viewList: 'فهرستی',
      viewCard: 'کارتی',
      noResultsTitle: 'رسانه‌ای یافت نشد',
      noResultsDesc: 'جستجو یا فیلترها را تغییر دهید.',
      errorLoading: 'بارگیری رسانه‌ها ناکام شد. دوباره تلاش کنید.',
      loadMore: 'بیشتر',
      results: '{{count}} مورد',
      by: 'توسط',
      views: 'بازدید',
      downloads: 'دانلود',
      featured: 'ویژه',
      view: 'مشاهده',
      detail: {
        back: 'بازگشت به مرکز رسانه‌ها',
        download: 'دانلود',
        downloading: 'در حال دانلود…',
        share: 'اشتراک‌گذاری',
        copied: 'لینک کاپی شد',
        preview: 'پیش‌نمایش',
        noPreview: 'پیش‌نمایش برای این نوع فایل موجود نیست. از دکمه دانلود استفاده کنید.',
        attachments: 'ضمیمه‌ها',
        related: 'رسانه‌های مرتبط',
        published: 'تاریخ نشر',
        department: 'دیپارتمنت',
        author: 'نویسنده',
        category: 'دسته',
        type: 'نوع',
        loadFailed: 'بارگیری این رسانه ناکام شد.',
        downloadFailed: 'دانلود ناکام شد. دوباره تلاش کنید.',
      },
    },
  },
  ps: {
    nav: { media: 'د رسنیو مرکز' },
    media: {
      title: 'د رسنیو مرکز',
      subtitle: 'له فارغانو سره شریک شوي عکسونه، ویډیوګانې، اسناد او خبرونه',
      searchPlaceholder: 'د سرلیک، ټګ یا کلیمې له مخې لټون…',
      filters: 'فلټرونه',
      clearFilters: 'فلټرونه پاک کړئ',
      allCategories: 'ټولې کټګورۍ',
      allTypes: 'ټول ډولونه',
      allMedia: 'ټولې رسنۍ',
      images: 'انځورونه',
      videos: 'ویډیوګانې',
      documents: 'اسناد',
      mediaType: 'د رسنۍ ډول',
      categories: 'کټګورۍ',
      dateRange: 'د نیټې موده',
      from: 'له',
      to: 'تر',
      currentSelection: 'اوسنی انتخاب',
      clearAll: 'ټول پاک کړئ',
      allDepartments: 'ټول څانګې',
      featuredOnly: 'یوازې ځانګړي',
      sort: 'ترتیب',
      sortNewest: 'تازه ترین',
      sortOldest: 'زاړه ترین',
      sortMostViewed: 'ډیر لیدل شوي',
      sortMostDownloaded: 'ډیر ښکته شوي',
      viewGrid: 'جال',
      viewList: 'لیست',
      viewCard: 'کارتونه',
      noResultsTitle: 'هیڅ رسنۍ ونه موندل شوه',
      noResultsDesc: 'لټون یا فلټرونه بدل کړئ.',
      errorLoading: 'د رسنیو راوستل ناکام شول. بیا هڅه وکړئ.',
      loadMore: 'نور',
      results: '{{count}} توکي',
      by: 'لخوا',
      views: 'لیدنې',
      downloads: 'ښکته کول',
      featured: 'ځانګړی',
      view: 'کتل',
      detail: {
        back: 'د رسنیو مرکز ته بیرته',
        download: 'ښکته کول',
        downloading: 'ښکته کیږي…',
        share: 'شریکول',
        copied: 'لینک کاپي شو',
        preview: 'مخکتنه',
        noPreview: 'د دې ډول فایل لپاره مخکتنه شتون نلري. د ښکته کولو تڼۍ وکاروئ.',
        attachments: 'ضمیمې',
        related: 'اړوندې رسنۍ',
        published: 'د خپرولو نیټه',
        department: 'څانګه',
        author: 'لیکوال',
        category: 'کټګوري',
        type: 'ډول',
        loadFailed: 'د دې رسنۍ راوستل ناکام شول.',
        downloadFailed: 'ښکته کول ناکام شول. بیا هڅه وکړئ.',
      },
    },
  },
};

export default media;
