// Mentorship feature: list, detail, mentees, applications, incoming requests.
const mentorship = {
  en: {
    mentorship: {
      common: {
        error: "Error",
        backToProfile: "Back to Profile",
      },
      status: {
        pending: "Pending",
        accepted: "Accepted",
        rejected: "Rejected",
      },
      contact: {
        email: "Email",
        whatsapp: "WhatsApp",
        message: "Message",
      },
      stats: {
        total: "Total",
      },
      faculties: {
        "Civil Engineering": "Civil Engineering",
        "Computer Science": "Computer Science",
        "Electromechanics": "Electromechanics",
        "Geomatics & Cadastre": "Geomatics & Cadastre",
        "Architecture": "Architecture",
        "Chemical Technology": "Chemical Technology",
        "Geology & Mines": "Geology & Mines",
        "Environmental Engineering": "Environmental Engineering",
      },
      expertise: {
        "Structural": "Structural",
        "Hydraulics": "Hydraulics",
        "AI/ML": "AI/ML",
        "Project Mgmt": "Project Mgmt",
        "GIS": "GIS",
        "Python": "Python",
        "Machine Learning": "Machine Learning",
      },
      filters: {
        title: "Filters",
        subtitle: "Find your perfect match",
        activeCount_one: "{{count}} active filter",
        activeCount_other: "{{count}} active filters",
        clearAll: "Clear all",
        faculty: "Faculty",
        experience: "Years of Experience",
        expertise: "Expertise Area",
        expAll: "All experience levels",
        exp5: "5+ years",
        exp10: "10+ years",
        exp15: "15+ years",
        resetAll: "Reset All Filters",
      },
      list: {
        heroBadge: "KPU Alumni Mentorship Hub",
        heroTitle: "Find Your Mentor",
        heroSubtitle: "Connect with experienced alumni and guide the next generation of KPU professionals.",
        searchPlaceholder: "Search by name, title, company, or expertise…",
        loading: "Loading…",
        showingPrefix: "Showing",
        showingOf: "of",
        mentorsLabel: "mentors",
        viewList: "List",
        viewGrid: "Grid",
        emptyTitle: "No mentors found",
        emptyText: "Try adjusting your search or removing some filters.",
        resetFilters: "Reset filters",
      },
      modal: {
        requestTitle: "Request Mentorship",
        whatsappLabel: "WhatsApp Number",
        optional: "(optional)",
        introLabel: "Introduction Message",
        introPlaceholder: "Tell the mentor what you'd like guidance on…",
        phoneError: "Please enter a valid phone number (digits, +, -, ( ) only).",
        sendRequest: "Send Request",
      },
      card: {
        noReviews: "No reviews yet",
        editProfile: "Edit Profile",
        mentorsCannotApplyTitle: "Mentors cannot apply for mentorship",
        mentorsCantApply: "Mentors Can't Apply",
        cancelRequestTitle: "Cancel request",
        cooldownTitle: "Cooldown: try again later",
        rejectedCount: "Rejected ({{count}}/3)",
        sending: "Sending…",
        requestAgainCount: "Request Again ({{count}}/3)",
        requestMentorship: "Request Mentorship",
        classOf: "Class of {{year}}",
        atCompany: "At {{company}}",
        yrsExp: "{{count}} yrs exp.",
        mentoredCount: "{{count}} mentored",
        view: "View",
        experienceLabel: "Experience",
        yrs: "{{count}} yrs",
        mentoredLabel: "Mentored",
        classLabel: "Class",
      },
      login: {
        title: "Login Required",
        requestText: "Please log in to request mentorship.",
        reviewText: "Please log in to leave a review.",
        goToLogin: "Go to Login",
      },
      mentorBlock: {
        title: "Mentors Cannot Apply",
        text: "You are registered as a mentor, so you cannot request mentorship from another mentor.",
      },
      cancel: {
        title: "Cancel Request?",
        confirm: "Cancel your mentorship request to {{name}}?",
        yes: "Yes, cancel",
        no: "No",
        cancelled: "Cancelled",
        failed: "Failed to cancel.",
        failedRequest: "Failed to cancel request.",
      },
      request: {
        sentTitle: "Request Sent",
        sentText: "Your request has been sent to {{name}}.",
        alreadyTitle: "Already Requested",
        cooldownTitle: "Cooldown Active",
        failed: "Failed to send request.",
      },
      review: {
        leaveReview: "Leave a Review",
        forName: "for {{name}}",
        yourRating: "Your Rating",
        selectRating: "Select a rating",
        selectRatingWarning: "Please select a rating",
        experienceLabel: "Your Experience",
        experiencePlaceholder: "Share how this mentor helped you…",
        submitReview: "Submit Review",
        thankYou: "Thank You",
        submitted: "Your review has been submitted.",
        failed: "Failed to submit review.",
        poor: "Poor",
        fair: "Fair",
        good: "Good",
        veryGood: "Very Good",
        excellent: "Excellent",
      },
      detail: {
        heroBadge: "Mentor Profile",
        heroTitle: "KPU Alumni Mentorship",
        heroSubtitle: "Connect with experienced alumni",
        allMentors: "All Mentors",
        loadError: "Could not load mentor profile.",
        notFoundTitle: "Mentor Not Found",
        notFoundText: "This mentor profile doesn't exist or has been removed.",
        backToMentors: "Back to Mentors",
        coverAlt: "Cover",
        verifiedMentor: "Verified mentor",
        rejectedTimes: "Rejected {{count}}/3 times",
        cancelRequest: "Cancel Request",
        leaveReview: "Leave Review",
        contactWhatsapp: "Contact on WhatsApp",
        statMentored: "Mentored",
        statYearsExp: "Years Exp.",
        statRating: "Rating",
        statGraduation: "Graduation",
        about: "About {{name}}",
        areasOfExpertise: "Areas of Expertise",
        reviews: "Reviews",
        writeReview: "Write Review",
        beFirstReview: "Be the first to share your experience",
        ratingOverview: "Rating Overview",
        basedOn: "Based on {{count}} reviews",
        quickInfo: "Quick Info",
        faculty: "Faculty",
        department: "Department",
        email: "Email",
        viewFullProfile: "View Full Profile",
      },
      mentees: {
        heroBadge: "My Mentees",
        heroTitle: "Alumni You Mentor",
        heroSubtitle: "Connect with and guide the next generation of KPU professionals",
        count_one: "{{count}} Mentee",
        count_other: "{{count}} Mentees",
        subtitle: "Connect and stay in touch with the alumni you mentor",
        searchPlaceholder: "Search mentees…",
        emptyTitle: "No mentees yet",
        emptyText: "When you accept mentorship requests, they will appear here.",
        viewPending: "View pending requests →",
      },
      applications: {
        heroBadge: "My Applications",
        heroTitle: "Mentorship Applications",
        heroSubtitle: "Track the mentorship requests you've sent to alumni mentors",
        emptyTitle: "No applications yet",
        browseMentors: "Browse Mentors",
        atCompany: "at {{company}}",
      },
      requests: {
        heroBadge: "Incoming Requests",
        heroTitle: "Mentorship Requests",
        heroSubtitle: "Review and respond to alumni seeking your guidance",
        tabAll: "All",
        searchPlaceholder: "Search…",
        emptyTitle: "No requests found",
        emptyText: "When someone requests mentorship, it will appear here.",
        acceptTitle: "Accept Mentorship",
        acceptHtml: "Set the mentorship end date. After this date, <strong>{{name}}</strong> will need to request again.",
        acceptBtn: "Accept",
        rejectBtn: "Reject",
        pickEndDate: "Please pick an end date",
        endDateFuture: "End date must be in the future",
        rejectTitle: "Reject Request?",
        rejectConfirm: "Reject the mentorship request from {{name}}?",
        doneTitle: "Done",
        activeUntil: "Mentorship active until {{date}}",
        rejected: "Request rejected.",
        updateFailed: "Failed to update request.",
      },
    },
  },

  da: {
    mentorship: {
      common: {
        error: "خطا",
        backToProfile: "بازگشت به پروفایل",
      },
      status: {
        pending: "در انتظار",
        accepted: "پذیرفته شد",
        rejected: "رد شد",
      },
      contact: {
        email: "ایمیل",
        whatsapp: "واتساپ",
        message: "پیام",
      },
      stats: {
        total: "مجموع",
      },
      faculties: {
        "Civil Engineering": "انجنیری ساختمانی",
        "Computer Science": "علوم کمپیوتر",
        "Electromechanics": "الکترومیخانیک",
        "Geomatics & Cadastre": "جیوماتیک و کدستر",
        "Architecture": "معماری",
        "Chemical Technology": "تکنالوژی کیمیاوی",
        "Geology & Mines": "جیولوژی و معادن",
        "Environmental Engineering": "انجنیری محیط زیست",
      },
      expertise: {
        "Structural": "ساختمانی",
        "Hydraulics": "هایدرولیک",
        "AI/ML": "هوش مصنوعی/یادگیری ماشین",
        "Project Mgmt": "مدیریت پروژه",
        "GIS": "سیستم اطلاعات جغرافیایی",
        "Python": "پایتون",
        "Machine Learning": "یادگیری ماشین",
      },
      filters: {
        title: "فیلترها",
        subtitle: "بهترین گزینه خود را پیدا کنید",
        activeCount_one: "{{count}} فیلتر فعال",
        activeCount_other: "{{count}} فیلتر فعال",
        clearAll: "پاک کردن همه",
        faculty: "پوهنځی",
        experience: "سال‌های تجربه",
        expertise: "ساحه تخصص",
        expAll: "همه سطوح تجربه",
        exp5: "۵+ سال",
        exp10: "۱۰+ سال",
        exp15: "۱۵+ سال",
        resetAll: "بازنشانی همه فیلترها",
      },
      list: {
        heroBadge: "مرکز رهنمایی فارغان KPU",
        heroTitle: "رهنمای خود را پیدا کنید",
        heroSubtitle: "با فارغان با تجربه ارتباط برقرار کنید و نسل بعدی متخصصان KPU را رهنمایی کنید.",
        searchPlaceholder: "جستجو بر اساس نام، عنوان، شرکت یا تخصص…",
        loading: "در حال بارگذاری…",
        showingPrefix: "نمایش",
        showingOf: "از",
        mentorsLabel: "رهنما",
        viewList: "لیست",
        viewGrid: "شبکه",
        emptyTitle: "هیچ رهنمایی یافت نشد",
        emptyText: "جستجوی خود را تنظیم کنید یا برخی فیلترها را حذف کنید.",
        resetFilters: "بازنشانی فیلترها",
      },
      modal: {
        requestTitle: "درخواست رهنمایی",
        whatsappLabel: "شماره واتساپ",
        optional: "(اختیاری)",
        introLabel: "پیام معرفی",
        introPlaceholder: "به رهنما بگویید در چه موردی به راهنمایی نیاز دارید…",
        phoneError: "لطفاً یک شماره تماس معتبر وارد کنید (فقط ارقام، +، -، ( ) ).",
        sendRequest: "ارسال درخواست",
      },
      card: {
        noReviews: "هنوز نظری ثبت نشده",
        editProfile: "ویرایش پروفایل",
        mentorsCannotApplyTitle: "رهنمایان نمی‌توانند درخواست رهنمایی بدهند",
        mentorsCantApply: "رهنمایان نمی‌توانند درخواست بدهند",
        cancelRequestTitle: "لغو درخواست",
        cooldownTitle: "زمان انتظار: بعداً دوباره تلاش کنید",
        rejectedCount: "رد شد ({{count}}/۳)",
        sending: "در حال ارسال…",
        requestAgainCount: "درخواست مجدد ({{count}}/۳)",
        requestMentorship: "درخواست رهنمایی",
        classOf: "فارغ سال {{year}}",
        atCompany: "در {{company}}",
        yrsExp: "{{count}} سال تجربه",
        mentoredCount: "{{count}} نفر رهنمایی شده",
        view: "مشاهده",
        experienceLabel: "تجربه",
        yrs: "{{count}} سال",
        mentoredLabel: "رهنمایی شده",
        classLabel: "دوره",
      },
      login: {
        title: "ورود لازم است",
        requestText: "برای درخواست رهنمایی لطفاً وارد شوید.",
        reviewText: "برای ثبت نظر لطفاً وارد شوید.",
        goToLogin: "رفتن به صفحه ورود",
      },
      mentorBlock: {
        title: "رهنمایان نمی‌توانند درخواست بدهند",
        text: "شما به عنوان رهنما ثبت شده‌اید، بنابراین نمی‌توانید از رهنمای دیگری درخواست رهنمایی کنید.",
      },
      cancel: {
        title: "لغو درخواست؟",
        confirm: "درخواست رهنمایی خود به {{name}} را لغو می‌کنید؟",
        yes: "بله، لغو شود",
        no: "نه",
        cancelled: "لغو شد",
        failed: "لغو ناموفق بود.",
        failedRequest: "لغو درخواست ناموفق بود.",
      },
      request: {
        sentTitle: "درخواست ارسال شد",
        sentText: "درخواست شما به {{name}} ارسال شد.",
        alreadyTitle: "قبلاً درخواست داده شده",
        cooldownTitle: "زمان انتظار فعال است",
        failed: "ارسال درخواست ناموفق بود.",
      },
      review: {
        leaveReview: "ثبت نظر",
        forName: "برای {{name}}",
        yourRating: "امتیاز شما",
        selectRating: "یک امتیاز انتخاب کنید",
        selectRatingWarning: "لطفاً یک امتیاز انتخاب کنید",
        experienceLabel: "تجربه شما",
        experiencePlaceholder: "بنویسید این رهنما چگونه به شما کمک کرد…",
        submitReview: "ثبت نظر",
        thankYou: "تشکر",
        submitted: "نظر شما ثبت شد.",
        failed: "ثبت نظر ناموفق بود.",
        poor: "ضعیف",
        fair: "متوسط",
        good: "خوب",
        veryGood: "خیلی خوب",
        excellent: "عالی",
      },
      detail: {
        heroBadge: "پروفایل رهنما",
        heroTitle: "رهنمایی فارغان KPU",
        heroSubtitle: "با فارغان با تجربه ارتباط برقرار کنید",
        allMentors: "همه رهنمایان",
        loadError: "بارگذاری پروفایل رهنما ممکن نشد.",
        notFoundTitle: "رهنما یافت نشد",
        notFoundText: "این پروفایل رهنما وجود ندارد یا حذف شده است.",
        backToMentors: "بازگشت به رهنمایان",
        coverAlt: "تصویر سرورق",
        verifiedMentor: "رهنمای تأیید شده",
        rejectedTimes: "{{count}}/۳ بار رد شده",
        cancelRequest: "لغو درخواست",
        leaveReview: "ثبت نظر",
        contactWhatsapp: "تماس از طریق واتساپ",
        statMentored: "رهنمایی شده",
        statYearsExp: "سال تجربه",
        statRating: "امتیاز",
        statGraduation: "فراغت",
        about: "درباره {{name}}",
        areasOfExpertise: "ساحات تخصص",
        reviews: "نظرات",
        writeReview: "نوشتن نظر",
        beFirstReview: "اولین نفری باشید که تجربه خود را به اشتراک می‌گذارد",
        ratingOverview: "خلاصه امتیازات",
        basedOn: "بر اساس {{count}} نظر",
        quickInfo: "معلومات سریع",
        faculty: "پوهنځی",
        department: "دیپارتمنت",
        email: "ایمیل",
        viewFullProfile: "مشاهده پروفایل کامل",
      },
      mentees: {
        heroBadge: "شاگردان من",
        heroTitle: "فارغانی که رهنمایی می‌کنید",
        heroSubtitle: "با نسل بعدی متخصصان KPU ارتباط برقرار کنید و آنان را رهنمایی کنید",
        count_one: "{{count}} شاگرد",
        count_other: "{{count}} شاگرد",
        subtitle: "با فارغانی که رهنمایی می‌کنید در ارتباط بمانید",
        searchPlaceholder: "جستجوی شاگردان…",
        emptyTitle: "هنوز شاگردی ندارید",
        emptyText: "وقتی درخواست‌های رهنمایی را بپذیرید، اینجا نمایش داده می‌شوند.",
        viewPending: "مشاهده درخواست‌های در انتظار ←",
      },
      applications: {
        heroBadge: "درخواست‌های من",
        heroTitle: "درخواست‌های رهنمایی",
        heroSubtitle: "درخواست‌های رهنمایی را که به رهنمایان فرستاده‌اید پیگیری کنید",
        emptyTitle: "هنوز درخواستی ندارید",
        browseMentors: "مرور رهنمایان",
        atCompany: "در {{company}}",
      },
      requests: {
        heroBadge: "درخواست‌های دریافتی",
        heroTitle: "درخواست‌های رهنمایی",
        heroSubtitle: "درخواست‌های فارغانی را که به دنبال راهنمایی شما هستند بررسی و پاسخ دهید",
        tabAll: "همه",
        searchPlaceholder: "جستجو…",
        emptyTitle: "درخواستی یافت نشد",
        emptyText: "وقتی کسی درخواست رهنمایی کند، اینجا نمایش داده می‌شود.",
        acceptTitle: "پذیرش رهنمایی",
        acceptHtml: "تاریخ پایان رهنمایی را تعیین کنید. پس از این تاریخ، <strong>{{name}}</strong> باید دوباره درخواست دهد.",
        acceptBtn: "پذیرش",
        rejectBtn: "رد",
        pickEndDate: "لطفاً یک تاریخ پایان انتخاب کنید",
        endDateFuture: "تاریخ پایان باید در آینده باشد",
        rejectTitle: "رد درخواست؟",
        rejectConfirm: "درخواست رهنمایی از {{name}} را رد می‌کنید؟",
        doneTitle: "انجام شد",
        activeUntil: "رهنمایی تا {{date}} فعال است",
        rejected: "درخواست رد شد.",
        updateFailed: "به‌روزرسانی درخواست ناموفق بود.",
      },
    },
  },

  ps: {
    mentorship: {
      common: {
        error: "تېروتنه",
        backToProfile: "پروفایل ته بیرته",
      },
      status: {
        pending: "په تمه",
        accepted: "ومنل شو",
        rejected: "رد شو",
      },
      contact: {
        email: "بریښنالیک",
        whatsapp: "واتساپ",
        message: "پیغام",
      },
      stats: {
        total: "ټول",
      },
      faculties: {
        "Civil Engineering": "ساختماني انجنیري",
        "Computer Science": "د کمپیوټر ساینس",
        "Electromechanics": "الکترومیخانیک",
        "Geomatics & Cadastre": "جیوماتیک او کدستر",
        "Architecture": "معماري",
        "Chemical Technology": "کیمیاوي ټکنالوژي",
        "Geology & Mines": "جیولوژي او کانونه",
        "Environmental Engineering": "د چاپیریال انجنیري",
      },
      expertise: {
        "Structural": "ساختماني",
        "Hydraulics": "هایدرولیک",
        "AI/ML": "مصنوعي ځیرکتیا/ماشیني زده‌کړه",
        "Project Mgmt": "د پروژې مدیریت",
        "GIS": "د جغرافیوي معلوماتو سیستم",
        "Python": "پایتون",
        "Machine Learning": "ماشیني زده‌کړه",
      },
      filters: {
        title: "فلټرونه",
        subtitle: "خپل غوره انتخاب ومومئ",
        activeCount_one: "{{count}} فعال فلټر",
        activeCount_other: "{{count}} فعال فلټرونه",
        clearAll: "ټول پاک کړئ",
        faculty: "پوهنځی",
        experience: "د تجربې کلونه",
        expertise: "د تخصص ساحه",
        expAll: "د تجربې ټولې کچې",
        exp5: "۵+ کاله",
        exp10: "۱۰+ کاله",
        exp15: "۱۵+ کاله",
        resetAll: "ټول فلټرونه بیا تنظیم کړئ",
      },
      list: {
        heroBadge: "د KPU فارغانو د لارښوونې مرکز",
        heroTitle: "خپل لارښود ومومئ",
        heroSubtitle: "د تجربه‌لرونکو فارغانو سره اړیکه ونیسئ او د KPU د مسلکي کسانو راتلونکی نسل لارښوونه وکړئ.",
        searchPlaceholder: "د نوم، عنوان، شرکت یا تخصص له مخې لټون…",
        loading: "بارېدل…",
        showingPrefix: "ښودل کیږي",
        showingOf: "له",
        mentorsLabel: "لارښود",
        viewList: "لیست",
        viewGrid: "جدول",
        emptyTitle: "هیڅ لارښود ونه موندل شو",
        emptyText: "خپل لټون سم کړئ یا یو څو فلټرونه لرې کړئ.",
        resetFilters: "فلټرونه بیا تنظیم کړئ",
      },
      modal: {
        requestTitle: "د لارښوونې غوښتنه",
        whatsappLabel: "د واتساپ شمیره",
        optional: "(اختیاري)",
        introLabel: "د پیژندنې پیغام",
        introPlaceholder: "لارښود ته ووایاست چې په کوم اړه لارښوونه غواړئ…",
        phoneError: "مهرباني وکړئ یوه سمه اړیکې شمیره ولیکئ (یوازې شمیرې، +، -، ( ) ).",
        sendRequest: "غوښتنه ولېږئ",
      },
      card: {
        noReviews: "تر اوسه هیڅ نظر نشته",
        editProfile: "پروفایل سمول",
        mentorsCannotApplyTitle: "لارښوونکي د لارښوونې غوښتنه نشي کولی",
        mentorsCantApply: "لارښوونکي غوښتنه نشي کولی",
        cancelRequestTitle: "غوښتنه لغوه کړئ",
        cooldownTitle: "د انتظار وخت: وروسته بیا هڅه وکړئ",
        rejectedCount: "رد شو ({{count}}/۳)",
        sending: "لیږل کیږي…",
        requestAgainCount: "بیا غوښتنه ({{count}}/۳)",
        requestMentorship: "د لارښوونې غوښتنه",
        classOf: "د {{year}} کال فارغ",
        atCompany: "په {{company}} کې",
        yrsExp: "{{count}} کاله تجربه",
        mentoredCount: "{{count}} کسانو ته لارښوونه",
        view: "کتل",
        experienceLabel: "تجربه",
        yrs: "{{count}} کاله",
        mentoredLabel: "لارښوونه شوي",
        classLabel: "دوره",
      },
      login: {
        title: "ننوتل اړین دي",
        requestText: "د لارښوونې د غوښتنې لپاره مهرباني وکړئ ننوځئ.",
        reviewText: "د نظر ثبتولو لپاره مهرباني وکړئ ننوځئ.",
        goToLogin: "ننوتلو ته لاړ شئ",
      },
      mentorBlock: {
        title: "لارښوونکي غوښتنه نشي کولی",
        text: "تاسو د لارښود په توګه ثبت شوي یاست، نو له بل لارښود څخه د لارښوونې غوښتنه نشئ کولی.",
      },
      cancel: {
        title: "غوښتنه لغوه شي؟",
        confirm: "{{name}} ته خپله د لارښوونې غوښتنه لغوه کوئ؟",
        yes: "هو، لغوه یې کړئ",
        no: "نه",
        cancelled: "لغوه شو",
        failed: "لغوه ناکام شو.",
        failedRequest: "د غوښتنې لغوه کول ناکام شول.",
      },
      request: {
        sentTitle: "غوښتنه ولېږل شوه",
        sentText: "ستاسو غوښتنه {{name}} ته ولېږل شوه.",
        alreadyTitle: "مخکې غوښتنه شوې",
        cooldownTitle: "د انتظار وخت فعال دی",
        failed: "د غوښتنې لیږل ناکام شول.",
      },
      review: {
        leaveReview: "نظر ثبت کړئ",
        forName: "د {{name}} لپاره",
        yourRating: "ستاسو درجه‌بندي",
        selectRating: "یوه درجه وټاکئ",
        selectRatingWarning: "مهرباني وکړئ یوه درجه وټاکئ",
        experienceLabel: "ستاسو تجربه",
        experiencePlaceholder: "ولیکئ چې دې لارښود تاسو سره څنګه مرسته وکړه…",
        submitReview: "نظر ثبت کړئ",
        thankYou: "مننه",
        submitted: "ستاسو نظر ثبت شو.",
        failed: "د نظر ثبتول ناکام شول.",
        poor: "ضعیف",
        fair: "منځنی",
        good: "ښه",
        veryGood: "ډیر ښه",
        excellent: "عالي",
      },
      detail: {
        heroBadge: "د لارښود پروفایل",
        heroTitle: "د KPU فارغانو لارښوونه",
        heroSubtitle: "د تجربه‌لرونکو فارغانو سره اړیکه ونیسئ",
        allMentors: "ټول لارښوونکي",
        loadError: "د لارښود پروفایل بار نشو.",
        notFoundTitle: "لارښود ونه موندل شو",
        notFoundText: "د دې لارښود پروفایل شتون نلري یا لرې شوی دی.",
        backToMentors: "لارښوونکو ته بیرته",
        coverAlt: "د سرپوښ انځور",
        verifiedMentor: "تایید شوی لارښود",
        rejectedTimes: "{{count}}/۳ ځله رد شوی",
        cancelRequest: "غوښتنه لغوه کړئ",
        leaveReview: "نظر ثبت کړئ",
        contactWhatsapp: "د واتساپ له لارې اړیکه",
        statMentored: "لارښوونه شوي",
        statYearsExp: "کاله تجربه",
        statRating: "درجه",
        statGraduation: "فراغت",
        about: "د {{name}} په اړه",
        areasOfExpertise: "د تخصص ساحې",
        reviews: "نظرونه",
        writeReview: "نظر ولیکئ",
        beFirstReview: "لومړی کس اوسئ چې خپله تجربه شریکوي",
        ratingOverview: "د درجو لنډیز",
        basedOn: "د {{count}} نظرونو پر بنسټ",
        quickInfo: "چټک معلومات",
        faculty: "پوهنځی",
        department: "څانګه",
        email: "بریښنالیک",
        viewFullProfile: "بشپړ پروفایل وګورئ",
      },
      mentees: {
        heroBadge: "زما زده‌کوونکي",
        heroTitle: "هغه فارغان چې لارښوونه یې کوئ",
        heroSubtitle: "د KPU د مسلکي کسانو راتلونکي نسل سره اړیکه ونیسئ او لارښوونه یې وکړئ",
        count_one: "{{count}} زده‌کوونکی",
        count_other: "{{count}} زده‌کوونکي",
        subtitle: "د هغو فارغانو سره چې لارښوونه یې کوئ په اړیکه کې پاتې شئ",
        searchPlaceholder: "د زده‌کوونکو لټون…",
        emptyTitle: "تر اوسه هیڅ زده‌کوونکی نشته",
        emptyText: "کله چې د لارښوونې غوښتنې ومنئ، دلته به ښکاره شي.",
        viewPending: "په تمه غوښتنې وګورئ ←",
      },
      applications: {
        heroBadge: "زما غوښتنې",
        heroTitle: "د لارښوونې غوښتنې",
        heroSubtitle: "هغه د لارښوونې غوښتنې وڅارئ چې فارغ لارښوونکو ته مو لېږلي دي",
        emptyTitle: "تر اوسه هیڅ غوښتنه نشته",
        browseMentors: "لارښوونکي وپلټئ",
        atCompany: "په {{company}} کې",
      },
      requests: {
        heroBadge: "راغلې غوښتنې",
        heroTitle: "د لارښوونې غوښتنې",
        heroSubtitle: "د هغو فارغانو غوښتنې وڅیړئ او ځواب ورکړئ چې ستاسو لارښوونه غواړي",
        tabAll: "ټول",
        searchPlaceholder: "لټون…",
        emptyTitle: "هیڅ غوښتنه ونه موندل شوه",
        emptyText: "کله چې څوک د لارښوونې غوښتنه وکړي، دلته به ښکاره شي.",
        acceptTitle: "د لارښوونې منل",
        acceptHtml: "د لارښوونې د پای نیټه وټاکئ. له دې نیټې وروسته، <strong>{{name}}</strong> باید بیا غوښتنه وکړي.",
        acceptBtn: "منل",
        rejectBtn: "رد",
        pickEndDate: "مهرباني وکړئ د پای نیټه وټاکئ",
        endDateFuture: "د پای نیټه باید په راتلونکي کې وي",
        rejectTitle: "غوښتنه رد شي؟",
        rejectConfirm: "د {{name}} د لارښوونې غوښتنه رد کوئ؟",
        doneTitle: "ترسره شو",
        activeUntil: "لارښوونه تر {{date}} پورې فعاله ده",
        rejected: "غوښتنه رد شوه.",
        updateFailed: "د غوښتنې تازه کول ناکام شول.",
      },
    },
  },
};

export default mentorship;
