// ProfilePage localization (profile namespace) — EN / Dari (da) / Pashto (ps)
const profile = {
  en: {
    profile: {
      time: {
        justNow: "Just now",
        minutesAgo: "{{n}}m ago",
        hoursAgo: "{{n}}h ago",
        daysAgo: "{{n}}d ago",
        monthsAgo: "{{n}}mo ago",
        yearsAgo: "{{n}}y ago",
      },
      errors: {
        loadProfile: "Failed to load profile.",
        uploadImage: "Failed to upload image.",
        cropImage: "Failed to crop image",
      },
      header: {
        addCoverPhoto: "Add Cover Photo",
        clickToUpload: "Click to upload",
        updateCover: "Update Cover",
        addCover: "Add Cover",
        addPhoto: "Add Photo",
        coverAlt: "Cover",
        profileAlt: "Profile",
        previewAlt: "Preview",
        verifiedAlumnus: "Verified Alumnus",
        verified: "Verified",
        pendingVerification: "Pending Verification",
        rejected: "Rejected",
        pending: "Pending",
        classOf: "Class of {{year}} · {{faculty}}",
        editProfile: "Edit Profile",
        editMentorProfile: "Edit Mentor Profile",
        becomeMentor: "Become a Mentor",
        editMentor: "Edit Mentor",
        beMentor: "Be a Mentor",
        sending: "Sending…",
        requestMentorship: "Request Mentorship",
        shareProfile: "Share Profile",
        updateProfileImage: "Update profile image",
      },
      a11y: {
        close: "Close",
        scrollLeft: "Scroll left",
        scrollRight: "Scroll right",
      },
      tabs: {
        overview: "Overview",
        jobs: "Applied Jobs",
        messages: "Messages",
        events: "Events",
        mentees: "My Mentees",
        requests: "Requests",
        applications: "My Applications",
      },
      contact: {
        title: "Contact Information",
        edit: "Edit",
        notAdded: "Not added",
        deletePhone: "Delete phone",
        deleteLocation: "Delete location",
        linkedinProfile: "LinkedIn Profile",
      },
      jobs: {
        title: "Applied Jobs",
        empty: "No job applications yet",
        browse: "Browse Jobs",
        jobTitleFallback: "Job Title",
        companyFallback: "Company",
        removeApplication: "Remove application",
        viewAll: "View All Applications ({{n}})",
        status: {
          pending: "pending",
        },
      },
      messages: {
        title: "Messages",
        viewAll: "View All",
        empty: "No messages yet",
        send: "Send Message",
        status: {
          pending: "Pending",
          received: "Received",
          responded: "Responded",
          unknown: "Unknown",
        },
        viewAllCount: "View All Messages ({{n}})",
      },
      events: {
        title: "Registered Events",
        viewAll: "View All",
        empty: "No registered events yet",
        browse: "Browse Events",
        eventTitleFallback: "Event Title",
        locationFallback: "Location",
        dateNotSet: "Date not set",
        viewCard: "View Card",
        card: "Card",
        viewAllCount: "View All Events ({{n}})",
        status: {
          registered: "registered",
        },
      },
      mentees: {
        title: "My Mentees",
        empty: "No mentees yet",
        emptyHint: "Accept mentorship requests to start mentoring",
        seeAll: "See all {{n}} mentees →",
      },
      requests: {
        title: "Mentorship Requests",
        pendingCount: "{{n}} pending",
        viewAll: "View all →",
        empty: "No mentorship requests yet",
        accept: "Accept",
        reject: "Reject",
        contactWhatsapp: "Contact on WhatsApp",
        status: {
          pending: "Pending",
          accepted: "Accepted",
          rejected: "Rejected",
        },
      },
      applications: {
        title: "My Mentor Applications",
        viewAll: "View all →",
        empty: "No applications sent yet",
        browse: "Browse Mentors",
        at: "At {{company}}",
        status: {
          pending: "Pending",
          accepted: "Accepted",
          rejected: "Rejected",
        },
      },
      about: {
        title: "About Me",
        empty: "No bio added yet.",
      },
      experience: {
        title: "Professional Experience",
        add: "Add",
        addItem: "Add Experience",
        empty: "No experience added yet.",
        viewAttachment: "View Attachment",
      },
      education: {
        title: "Education",
        add: "Add",
        addItem: "Add Education",
        empty: "No education added yet.",
        viewAttachment: "View Attachment",
      },
      skills: {
        title: "Skills & Expertise",
        add: "Add",
        addItem: "Add Skill",
        empty: "No skills added yet.",
        proficiencyOutOf: "{{n}}/5",
        view: "View",
      },
      achievements: {
        title: "Achievements & Awards",
        add: "Add",
        addItem: "Add Achievement",
        empty: "No achievements added yet.",
        totalAchievements: "Total Achievements",
        latestYear: "Latest Year",
        latestCategory: "Latest Category",
        viewAttachment: "View Attachment",
      },
      common: {
        cancel: "Cancel",
        save: "Save",
        saving: "Saving...",
        edit: "Edit",
        delete: "Delete",
        chooseFile: "Choose File",
        noFileSelected: "No file selected",
        viewCurrentAttachment: "View Current Attachment",
      },
      modals: {
        editProfile: "Edit Profile",
        cropImage: "Crop Image",
        cropAndUpload: "Crop & Upload",
        zoom: "Zoom",
        editExperience: "Edit Experience",
        addExperience: "Add Experience",
        editEducation: "Edit Education",
        addEducation: "Add Education",
        editSkill: "Edit Skill",
        addSkill: "Add Skill",
        editAchievement: "Edit Achievement",
        addAchievement: "Add Achievement",
        editContact: "Edit Contact Information",
        share: "Share Profile",
        editMentorProfile: "Edit Mentor Profile",
        becomeMentor: "Become a Mentor",
      },
      fields: {
        name: "Full Name",
        phone: "Phone",
        currentJobTitle: "Current Job Title",
        currentCompany: "Current Company",
        location: "Location",
        linkedin: "LinkedIn",
        bio: "Bio",
        jobTitleRequired: "Job Title *",
        company: "Company",
        startDate: "Start Date",
        endDate: "End Date",
        currentlyWorkHere: "I currently work here",
        description: "Description",
        attachment: "Attachment",
        institutionRequired: "Institution *",
        degree: "Degree",
        fieldOfStudy: "Field of Study",
        startYear: "Start Year",
        endYear: "End Year",
        grade: "Grade",
        skillNameRequired: "Skill Name *",
        category: "Category",
        proficiency: "Proficiency (1-5)",
        titleRequired: "Title *",
        issuer: "Issuer",
        year: "Year",
        phoneNumber: "Phone Number",
        enterPhone: "Enter your phone number",
        enterLocation: "Enter your location",
        jobTitle: "Job Title",
        companyOrg: "Company / Organization",
        faculty: "Faculty",
        yearsOfExperience: "Years of Experience",
        mentorBio: "Mentor Bio",
        expertiseAreas: "Expertise Areas",
      },
      placeholders: {
        jobTitle: "e.g. Senior Engineer",
        company: "e.g. Kabul Tech",
        years: "e.g. 5",
        mentorBio: "Tell mentees what you can help with...",
        expertise: "e.g. Machine Learning",
      },
      faculties: {
        select: "Select faculty",
        civil: "Civil Engineering",
        cs: "Computer Science",
        electromechanics: "Electromechanics",
        geomatics: "Geomatics",
        architecture: "Architecture",
        other: "Other",
      },
      share: {
        classOf: "Class of {{year}} · {{faculty}}",
        profileLink: "Profile link",
        copied: "Copied",
        copy: "Copy",
        shareVia: "Share via",
        shareViaPlatform: "Share via {{platform}}",
      },
      mentor: {
        imageNote: "Profile image will be shown in the mentorship directory",
        add: "Add",
        removeProfile: "Remove Mentor Profile",
      },
      alerts: {
        removeApplicationTitle: "Remove Application?",
        removeApplicationHtml: "Are you sure you want to remove your application for <strong>{{title}}</strong>?",
        yesRemove: "Yes, remove it",
        cancel: "Cancel",
        applicationRemovedTitle: "Application Removed",
        applicationRemovedText: "Your job application has been removed successfully.",
        error: "Error",
        removeApplicationError: "Failed to remove application. Please try again.",
        saveMentorError: "Failed to save mentor profile.",
        mentorSavedTitle: "Mentor profile saved!",
        removeMentorTitle: "Remove mentor profile?",
        removeMentorText: "You will no longer appear in the mentorship directory.",
        yesRemoveShort: "Yes, remove",
        removeMentorError: "Failed to remove mentor profile.",
        requestMentorshipTitle: "Request Mentorship",
        requestMentorshipIntro: "Send a request to <strong>{{name}}</strong>",
        whatsappPlaceholder: "WhatsApp number (optional)",
        introducePlaceholder: "Introduce yourself and explain what you'd like guidance on... (optional)",
        sendRequest: "Send Request",
        requestSentTitle: "Request Sent!",
        requestSentText: "Your mentorship request has been sent to {{name}}. They will get back to you soon.",
        alreadyRequestedTitle: "Already Requested",
        sendRequestError: "Failed to send request.",
        saveChangesError: "Failed to save changes.",
        saveExperienceError: "Failed to save experience.",
        areYouSure: "Are you sure?",
        deleteExperienceText: "Do you want to delete this experience?",
        yesDelete: "Yes, delete it!",
        deletedTitle: "Deleted!",
        experienceDeleted: "Experience has been deleted.",
        deleteExperienceError: "Failed to delete experience.",
        saveEducationError: "Failed to save education.",
        deleteEducationText: "Do you want to delete this education?",
        educationDeleted: "Education has been deleted.",
        deleteEducationError: "Failed to delete education.",
        saveSkillError: "Failed to save skill.",
        deleteSkillText: "Do you want to delete this skill?",
        skillDeleted: "Skill has been deleted.",
        deleteSkillError: "Failed to delete skill.",
        saveAchievementError: "Failed to save achievement.",
        deleteAchievementText: "Do you want to delete this achievement?",
        achievementDeleted: "Achievement has been deleted.",
        deleteAchievementError: "Failed to delete achievement.",
        updateContactError: "Failed to update contact information.",
        deleteContactText: "Do you want to remove your {{field}} information?",
        yesRemoveIt: "Yes, remove it!",
        removedTitle: "Removed!",
        contactRemoved: "{{field}} information has been removed.",
        removeContactError: "Failed to remove contact information.",
        acceptMentorshipTitle: "Accept Mentorship",
        acceptMentorshipHtml: "Set the mentorship end date. After this date, <strong>{{name}}</strong> will need to request again.",
        accept: "Accept",
        pickEndDate: "Please pick an end date",
        endDateFuture: "End date must be in the future",
        acceptedTitle: "Accepted",
        mentorshipActiveUntil: "Mentorship active until {{date}}",
        failed: "Failed",
        rejectedTitle: "Rejected",
      },
    },
  },

  da: {
    profile: {
      time: {
        justNow: "همین حالا",
        minutesAgo: "{{n}} دقیقه پیش",
        hoursAgo: "{{n}} ساعت پیش",
        daysAgo: "{{n}} روز پیش",
        monthsAgo: "{{n}} ماه پیش",
        yearsAgo: "{{n}} سال پیش",
      },
      errors: {
        loadProfile: "بارگذاری پروفایل ناکام شد.",
        uploadImage: "بارگذاری تصویر ناکام شد.",
        cropImage: "برش تصویر ناکام شد",
      },
      header: {
        addCoverPhoto: "افزودن عکس پس‌زمینه",
        clickToUpload: "برای بارگذاری کلیک کنید",
        updateCover: "بروزرسانی پس‌زمینه",
        addCover: "افزودن پس‌زمینه",
        addPhoto: "افزودن عکس",
        coverAlt: "پس‌زمینه",
        profileAlt: "پروفایل",
        previewAlt: "پیش‌نمایش",
        verifiedAlumnus: "فارغ تأیید‌شده",
        verified: "تأیید‌شده",
        pendingVerification: "در انتظار تأیید",
        rejected: "رد‌شده",
        pending: "در انتظار",
        classOf: "دوره {{year}} · {{faculty}}",
        editProfile: "ویرایش پروفایل",
        editMentorProfile: "ویرایش پروفایل رهنما",
        becomeMentor: "رهنما شوید",
        editMentor: "ویرایش رهنما",
        beMentor: "رهنما شوید",
        sending: "در حال ارسال…",
        requestMentorship: "درخواست رهنمایی",
        shareProfile: "اشتراک پروفایل",
        updateProfileImage: "بروزرسانی تصویر پروفایل",
      },
      a11y: {
        close: "بستن",
        scrollLeft: "حرکت به چپ",
        scrollRight: "حرکت به راست",
      },
      tabs: {
        overview: "نمای کلی",
        jobs: "وظایف درخواست‌شده",
        messages: "پیام‌ها",
        events: "رویدادها",
        mentees: "شاگردان من",
        requests: "درخواست‌ها",
        applications: "درخواست‌های من",
      },
      contact: {
        title: "معلومات تماس",
        edit: "ویرایش",
        notAdded: "اضافه نشده",
        deletePhone: "حذف تلفن",
        deleteLocation: "حذف موقعیت",
        linkedinProfile: "پروفایل لینکدین",
      },
      jobs: {
        title: "وظایف درخواست‌شده",
        empty: "هنوز هیچ درخواست وظیفه‌ای وجود ندارد",
        browse: "مرور وظایف",
        jobTitleFallback: "عنوان وظیفه",
        companyFallback: "شرکت",
        removeApplication: "حذف درخواست",
        viewAll: "مشاهده همه درخواست‌ها ({{n}})",
        status: {
          pending: "در انتظار",
        },
      },
      messages: {
        title: "پیام‌ها",
        viewAll: "مشاهده همه",
        empty: "هنوز هیچ پیامی وجود ندارد",
        send: "ارسال پیام",
        status: {
          pending: "در انتظار",
          received: "دریافت‌شده",
          responded: "پاسخ‌داده‌شده",
          unknown: "نامعلوم",
        },
        viewAllCount: "مشاهده همه پیام‌ها ({{n}})",
      },
      events: {
        title: "رویدادهای ثبت‌نام‌شده",
        viewAll: "مشاهده همه",
        empty: "هنوز هیچ رویداد ثبت‌نام‌شده‌ای وجود ندارد",
        browse: "مرور رویدادها",
        eventTitleFallback: "عنوان رویداد",
        locationFallback: "موقعیت",
        dateNotSet: "تاریخ تعیین نشده",
        viewCard: "مشاهده کارت",
        card: "کارت",
        viewAllCount: "مشاهده همه رویدادها ({{n}})",
        status: {
          registered: "ثبت‌نام‌شده",
        },
      },
      mentees: {
        title: "شاگردان من",
        empty: "هنوز شاگردی ندارید",
        emptyHint: "برای شروع رهنمایی، درخواست‌های رهنمایی را بپذیرید",
        seeAll: "مشاهده همه {{n}} شاگرد →",
      },
      requests: {
        title: "درخواست‌های رهنمایی",
        pendingCount: "{{n}} در انتظار",
        viewAll: "مشاهده همه →",
        empty: "هنوز هیچ درخواست رهنمایی وجود ندارد",
        accept: "پذیرفتن",
        reject: "رد کردن",
        contactWhatsapp: "تماس از طریق واتساپ",
        status: {
          pending: "در انتظار",
          accepted: "پذیرفته‌شده",
          rejected: "رد‌شده",
        },
      },
      applications: {
        title: "درخواست‌های رهنمایی من",
        viewAll: "مشاهده همه →",
        empty: "هنوز هیچ درخواستی ارسال نشده است",
        browse: "مرور رهنمایان",
        at: "در {{company}}",
        status: {
          pending: "در انتظار",
          accepted: "پذیرفته‌شده",
          rejected: "رد‌شده",
        },
      },
      about: {
        title: "درباره من",
        empty: "هنوز بیوگرافی اضافه نشده است.",
      },
      experience: {
        title: "تجربه مسلکی",
        add: "افزودن",
        addItem: "افزودن تجربه",
        empty: "هنوز تجربه‌ای اضافه نشده است.",
        viewAttachment: "مشاهده ضمیمه",
      },
      education: {
        title: "تحصیلات",
        add: "افزودن",
        addItem: "افزودن تحصیلات",
        empty: "هنوز تحصیلاتی اضافه نشده است.",
        viewAttachment: "مشاهده ضمیمه",
      },
      skills: {
        title: "مهارت‌ها و تخصص",
        add: "افزودن",
        addItem: "افزودن مهارت",
        empty: "هنوز مهارتی اضافه نشده است.",
        proficiencyOutOf: "{{n}}/۵",
        view: "مشاهده",
      },
      achievements: {
        title: "دستاوردها و جوایز",
        add: "افزودن",
        addItem: "افزودن دستاورد",
        empty: "هنوز دستاوردی اضافه نشده است.",
        totalAchievements: "مجموع دستاوردها",
        latestYear: "آخرین سال",
        latestCategory: "آخرین دسته‌بندی",
        viewAttachment: "مشاهده ضمیمه",
      },
      common: {
        cancel: "لغو",
        save: "ذخیره",
        saving: "در حال ذخیره...",
        edit: "ویرایش",
        delete: "حذف",
        chooseFile: "انتخاب فایل",
        noFileSelected: "هیچ فایلی انتخاب نشده",
        viewCurrentAttachment: "مشاهده ضمیمه فعلی",
      },
      modals: {
        editProfile: "ویرایش پروفایل",
        cropImage: "برش تصویر",
        cropAndUpload: "برش و بارگذاری",
        zoom: "بزرگنمایی",
        editExperience: "ویرایش تجربه",
        addExperience: "افزودن تجربه",
        editEducation: "ویرایش تحصیلات",
        addEducation: "افزودن تحصیلات",
        editSkill: "ویرایش مهارت",
        addSkill: "افزودن مهارت",
        editAchievement: "ویرایش دستاورد",
        addAchievement: "افزودن دستاورد",
        editContact: "ویرایش معلومات تماس",
        share: "اشتراک پروفایل",
        editMentorProfile: "ویرایش پروفایل رهنما",
        becomeMentor: "رهنما شوید",
      },
      fields: {
        name: "نام کامل",
        phone: "تلفن",
        currentJobTitle: "عنوان وظیفه فعلی",
        currentCompany: "شرکت فعلی",
        location: "موقعیت",
        linkedin: "لینکدین",
        bio: "بیوگرافی",
        jobTitleRequired: "عنوان وظیفه *",
        company: "شرکت",
        startDate: "تاریخ شروع",
        endDate: "تاریخ پایان",
        currentlyWorkHere: "در حال حاضر اینجا کار می‌کنم",
        description: "توضیحات",
        attachment: "ضمیمه",
        institutionRequired: "مؤسسه *",
        degree: "درجه تحصیلی",
        fieldOfStudy: "رشته تحصیلی",
        startYear: "سال شروع",
        endYear: "سال پایان",
        grade: "نمره",
        skillNameRequired: "نام مهارت *",
        category: "دسته‌بندی",
        proficiency: "مهارت (۱-۵)",
        titleRequired: "عنوان *",
        issuer: "صادرکننده",
        year: "سال",
        phoneNumber: "شماره تلفن",
        enterPhone: "شماره تلفن خود را وارد کنید",
        enterLocation: "موقعیت خود را وارد کنید",
        jobTitle: "عنوان وظیفه",
        companyOrg: "شرکت / سازمان",
        faculty: "پوهنځی",
        yearsOfExperience: "سال‌های تجربه",
        mentorBio: "بیوگرافی رهنما",
        expertiseAreas: "حوزه‌های تخصص",
      },
      placeholders: {
        jobTitle: "مثلاً انجنیر ارشد",
        company: "مثلاً کابل تک",
        years: "مثلاً ۵",
        mentorBio: "به شاگردان بگویید در چه مواردی می‌توانید کمک کنید...",
        expertise: "مثلاً یادگیری ماشین",
      },
      faculties: {
        select: "انتخاب پوهنځی",
        civil: "انجنیری ساختمانی",
        cs: "کمپیوتر ساینس",
        electromechanics: "الکترومیخانیک",
        geomatics: "جیوماتیک",
        architecture: "آرشیتکت",
        other: "سایر",
      },
      share: {
        classOf: "دوره {{year}} · {{faculty}}",
        profileLink: "لینک پروفایل",
        copied: "کاپی شد",
        copy: "کاپی",
        shareVia: "اشتراک از طریق",
        shareViaPlatform: "اشتراک از طریق {{platform}}",
      },
      mentor: {
        imageNote: "تصویر پروفایل در دایرکتوری رهنمایی نمایش داده می‌شود",
        add: "افزودن",
        removeProfile: "حذف پروفایل رهنما",
      },
      alerts: {
        removeApplicationTitle: "حذف درخواست؟",
        removeApplicationHtml: "آیا مطمئن هستید که می‌خواهید درخواست خود را برای <strong>{{title}}</strong> حذف کنید؟",
        yesRemove: "بله، حذف شود",
        cancel: "لغو",
        applicationRemovedTitle: "درخواست حذف شد",
        applicationRemovedText: "درخواست وظیفه شما با موفقیت حذف شد.",
        error: "خطا",
        removeApplicationError: "حذف درخواست ناکام شد. لطفاً دوباره تلاش کنید.",
        saveMentorError: "ذخیره پروفایل رهنما ناکام شد.",
        mentorSavedTitle: "پروفایل رهنما ذخیره شد!",
        removeMentorTitle: "حذف پروفایل رهنما؟",
        removeMentorText: "دیگر در دایرکتوری رهنمایی ظاهر نخواهید شد.",
        yesRemoveShort: "بله، حذف شود",
        removeMentorError: "حذف پروفایل رهنما ناکام شد.",
        requestMentorshipTitle: "درخواست رهنمایی",
        requestMentorshipIntro: "ارسال درخواست به <strong>{{name}}</strong>",
        whatsappPlaceholder: "شماره واتساپ (اختیاری)",
        introducePlaceholder: "خود را معرفی کنید و توضیح دهید در چه موردی نیاز به رهنمایی دارید... (اختیاری)",
        sendRequest: "ارسال درخواست",
        requestSentTitle: "درخواست ارسال شد!",
        requestSentText: "درخواست رهنمایی شما به {{name}} ارسال شد. به‌زودی با شما در تماس خواهند شد.",
        alreadyRequestedTitle: "قبلاً درخواست داده‌اید",
        sendRequestError: "ارسال درخواست ناکام شد.",
        saveChangesError: "ذخیره تغییرات ناکام شد.",
        saveExperienceError: "ذخیره تجربه ناکام شد.",
        areYouSure: "آیا مطمئن هستید؟",
        deleteExperienceText: "آیا می‌خواهید این تجربه را حذف کنید؟",
        yesDelete: "بله، حذف شود!",
        deletedTitle: "حذف شد!",
        experienceDeleted: "تجربه حذف شد.",
        deleteExperienceError: "حذف تجربه ناکام شد.",
        saveEducationError: "ذخیره تحصیلات ناکام شد.",
        deleteEducationText: "آیا می‌خواهید این تحصیلات را حذف کنید؟",
        educationDeleted: "تحصیلات حذف شد.",
        deleteEducationError: "حذف تحصیلات ناکام شد.",
        saveSkillError: "ذخیره مهارت ناکام شد.",
        deleteSkillText: "آیا می‌خواهید این مهارت را حذف کنید؟",
        skillDeleted: "مهارت حذف شد.",
        deleteSkillError: "حذف مهارت ناکام شد.",
        saveAchievementError: "ذخیره دستاورد ناکام شد.",
        deleteAchievementText: "آیا می‌خواهید این دستاورد را حذف کنید؟",
        achievementDeleted: "دستاورد حذف شد.",
        deleteAchievementError: "حذف دستاورد ناکام شد.",
        updateContactError: "بروزرسانی معلومات تماس ناکام شد.",
        deleteContactText: "آیا می‌خواهید معلومات {{field}} خود را حذف کنید؟",
        yesRemoveIt: "بله، حذف شود!",
        removedTitle: "حذف شد!",
        contactRemoved: "معلومات {{field}} حذف شد.",
        removeContactError: "حذف معلومات تماس ناکام شد.",
        acceptMentorshipTitle: "پذیرفتن رهنمایی",
        acceptMentorshipHtml: "تاریخ پایان رهنمایی را تعیین کنید. پس از این تاریخ، <strong>{{name}}</strong> باید دوباره درخواست دهد.",
        accept: "پذیرفتن",
        pickEndDate: "لطفاً یک تاریخ پایان انتخاب کنید",
        endDateFuture: "تاریخ پایان باید در آینده باشد",
        acceptedTitle: "پذیرفته شد",
        mentorshipActiveUntil: "رهنمایی فعال تا {{date}}",
        failed: "ناکام شد",
        rejectedTitle: "رد شد",
      },
    },
  },

  ps: {
    profile: {
      time: {
        justNow: "همدا اوس",
        minutesAgo: "{{n}} دقیقې مخکې",
        hoursAgo: "{{n}} ساعته مخکې",
        daysAgo: "{{n}} ورځې مخکې",
        monthsAgo: "{{n}} میاشتې مخکې",
        yearsAgo: "{{n}} کاله مخکې",
      },
      errors: {
        loadProfile: "د پروفایل بارول ناکام شول.",
        uploadImage: "د انځور پورته کول ناکام شول.",
        cropImage: "د انځور پرې کول ناکام شول",
      },
      header: {
        addCoverPhoto: "د پوښ انځور اضافه کړئ",
        clickToUpload: "د پورته کولو لپاره کلیک وکړئ",
        updateCover: "پوښ نوی کړئ",
        addCover: "پوښ اضافه کړئ",
        addPhoto: "انځور اضافه کړئ",
        coverAlt: "پوښ",
        profileAlt: "پروفایل",
        previewAlt: "مخکتنه",
        verifiedAlumnus: "تایید شوی فارغ",
        verified: "تایید شوی",
        pendingVerification: "د تایید په تمه",
        rejected: "رد شوی",
        pending: "په تمه",
        classOf: "د {{year}} دوره · {{faculty}}",
        editProfile: "پروفایل سمول",
        editMentorProfile: "د لارښود پروفایل سمول",
        becomeMentor: "لارښود شئ",
        editMentor: "لارښود سمول",
        beMentor: "لارښود شئ",
        sending: "لیږل کیږي…",
        requestMentorship: "د لارښوونې غوښتنه",
        shareProfile: "پروفایل شریک کړئ",
        updateProfileImage: "د پروفایل انځور نوی کړئ",
      },
      a11y: {
        close: "بندول",
        scrollLeft: "کیڼ ته حرکت",
        scrollRight: "ښي ته حرکت",
      },
      tabs: {
        overview: "لنډه کتنه",
        jobs: "غوښتل شوې دندې",
        messages: "پیغامونه",
        events: "پیښې",
        mentees: "زما زده‌کوونکي",
        requests: "غوښتنې",
        applications: "زما غوښتنلیکونه",
      },
      contact: {
        title: "د اړیکې معلومات",
        edit: "سمول",
        notAdded: "اضافه شوی نه دی",
        deletePhone: "تلیفون ړنګول",
        deleteLocation: "موقعیت ړنګول",
        linkedinProfile: "د لینکډین پروفایل",
      },
      jobs: {
        title: "غوښتل شوې دندې",
        empty: "تر اوسه د دندې غوښتنلیک نشته",
        browse: "دندې وګورئ",
        jobTitleFallback: "د دندې عنوان",
        companyFallback: "شرکت",
        removeApplication: "غوښتنلیک لرې کول",
        viewAll: "ټول غوښتنلیکونه وګورئ ({{n}})",
        status: {
          pending: "په تمه",
        },
      },
      messages: {
        title: "پیغامونه",
        viewAll: "ټول وګورئ",
        empty: "تر اوسه پیغام نشته",
        send: "پیغام ولیږئ",
        status: {
          pending: "په تمه",
          received: "ترلاسه شوی",
          responded: "ځواب شوی",
          unknown: "نامعلوم",
        },
        viewAllCount: "ټول پیغامونه وګورئ ({{n}})",
      },
      events: {
        title: "نوم‌لیکل شوې پیښې",
        viewAll: "ټول وګورئ",
        empty: "تر اوسه نوم‌لیکل شوې پیښه نشته",
        browse: "پیښې وګورئ",
        eventTitleFallback: "د پیښې عنوان",
        locationFallback: "موقعیت",
        dateNotSet: "نېټه ټاکل شوې نه ده",
        viewCard: "کارت وګورئ",
        card: "کارت",
        viewAllCount: "ټولې پیښې وګورئ ({{n}})",
        status: {
          registered: "نوم‌لیکل شوی",
        },
      },
      mentees: {
        title: "زما زده‌کوونکي",
        empty: "تر اوسه زده‌کوونکی نشته",
        emptyHint: "د لارښوونې پیل لپاره د لارښوونې غوښتنې ومنئ",
        seeAll: "ټول {{n}} زده‌کوونکي وګورئ →",
      },
      requests: {
        title: "د لارښوونې غوښتنې",
        pendingCount: "{{n}} په تمه",
        viewAll: "ټول وګورئ →",
        empty: "تر اوسه د لارښوونې غوښتنه نشته",
        accept: "منل",
        reject: "ردول",
        contactWhatsapp: "د واتساپ له لارې اړیکه",
        status: {
          pending: "په تمه",
          accepted: "منل شوی",
          rejected: "رد شوی",
        },
      },
      applications: {
        title: "زما د لارښوونې غوښتنلیکونه",
        viewAll: "ټول وګورئ →",
        empty: "تر اوسه غوښتنلیک نه دی لیږل شوی",
        browse: "لارښوونکي وګورئ",
        at: "په {{company}} کې",
        status: {
          pending: "په تمه",
          accepted: "منل شوی",
          rejected: "رد شوی",
        },
      },
      about: {
        title: "زما په اړه",
        empty: "تر اوسه بیوګرافي نه ده اضافه شوې.",
      },
      experience: {
        title: "مسلکي تجربه",
        add: "اضافه کول",
        addItem: "تجربه اضافه کړئ",
        empty: "تر اوسه تجربه نه ده اضافه شوې.",
        viewAttachment: "ضمیمه وګورئ",
      },
      education: {
        title: "زده‌کړه",
        add: "اضافه کول",
        addItem: "زده‌کړه اضافه کړئ",
        empty: "تر اوسه زده‌کړه نه ده اضافه شوې.",
        viewAttachment: "ضمیمه وګورئ",
      },
      skills: {
        title: "مهارتونه او تخصص",
        add: "اضافه کول",
        addItem: "مهارت اضافه کړئ",
        empty: "تر اوسه مهارت نه دی اضافه شوی.",
        proficiencyOutOf: "{{n}}/۵",
        view: "وګورئ",
      },
      achievements: {
        title: "لاسته‌راوړنې او جایزې",
        add: "اضافه کول",
        addItem: "لاسته‌راوړنه اضافه کړئ",
        empty: "تر اوسه لاسته‌راوړنه نه ده اضافه شوې.",
        totalAchievements: "ټولې لاسته‌راوړنې",
        latestYear: "وروستی کال",
        latestCategory: "وروستۍ کټګوري",
        viewAttachment: "ضمیمه وګورئ",
      },
      common: {
        cancel: "لغوه",
        save: "ثبت",
        saving: "ثبتیږي...",
        edit: "سمول",
        delete: "ړنګول",
        chooseFile: "فایل وټاکئ",
        noFileSelected: "هیڅ فایل نه دی ټاکل شوی",
        viewCurrentAttachment: "اوسنۍ ضمیمه وګورئ",
      },
      modals: {
        editProfile: "پروفایل سمول",
        cropImage: "انځور پرې کول",
        cropAndUpload: "پرې کول او پورته کول",
        zoom: "لویول",
        editExperience: "تجربه سمول",
        addExperience: "تجربه اضافه کړئ",
        editEducation: "زده‌کړه سمول",
        addEducation: "زده‌کړه اضافه کړئ",
        editSkill: "مهارت سمول",
        addSkill: "مهارت اضافه کړئ",
        editAchievement: "لاسته‌راوړنه سمول",
        addAchievement: "لاسته‌راوړنه اضافه کړئ",
        editContact: "د اړیکې معلومات سمول",
        share: "پروفایل شریک کړئ",
        editMentorProfile: "د لارښود پروفایل سمول",
        becomeMentor: "لارښود شئ",
      },
      fields: {
        name: "بشپړ نوم",
        phone: "تلیفون",
        currentJobTitle: "د اوسنۍ دندې عنوان",
        currentCompany: "اوسنی شرکت",
        location: "موقعیت",
        linkedin: "لینکډین",
        bio: "بیوګرافي",
        jobTitleRequired: "د دندې عنوان *",
        company: "شرکت",
        startDate: "د پیل نېټه",
        endDate: "د پای نېټه",
        currentlyWorkHere: "زه اوس مهال دلته کار کوم",
        description: "تشریح",
        attachment: "ضمیمه",
        institutionRequired: "مؤسسه *",
        degree: "درجه",
        fieldOfStudy: "د زده‌کړې څانګه",
        startYear: "د پیل کال",
        endYear: "د پای کال",
        grade: "نمره",
        skillNameRequired: "د مهارت نوم *",
        category: "کټګوري",
        proficiency: "مهارت (۱-۵)",
        titleRequired: "عنوان *",
        issuer: "صادروونکی",
        year: "کال",
        phoneNumber: "د تلیفون شمیره",
        enterPhone: "خپله د تلیفون شمیره دننه کړئ",
        enterLocation: "خپل موقعیت دننه کړئ",
        jobTitle: "د دندې عنوان",
        companyOrg: "شرکت / اداره",
        faculty: "پوهنځی",
        yearsOfExperience: "د تجربې کلونه",
        mentorBio: "د لارښود بیوګرافي",
        expertiseAreas: "د تخصص ساحې",
      },
      placeholders: {
        jobTitle: "لکه ارشد انجنیر",
        company: "لکه کابل ټیک",
        years: "لکه ۵",
        mentorBio: "زده‌کوونکو ته ووایاست چې په څه کې مرسته کولای شئ...",
        expertise: "لکه د ماشین زده‌کړه",
      },
      faculties: {
        select: "پوهنځی وټاکئ",
        civil: "ساختماني انجنیري",
        cs: "کمپیوټر ساینس",
        electromechanics: "الکترومیخانیک",
        geomatics: "جیوماتیک",
        architecture: "ارشیتکت",
        other: "نور",
      },
      share: {
        classOf: "د {{year}} دوره · {{faculty}}",
        profileLink: "د پروفایل لینک",
        copied: "کاپي شو",
        copy: "کاپي",
        shareVia: "شریک کړئ له لارې",
        shareViaPlatform: "د {{platform}} له لارې شریک کړئ",
      },
      mentor: {
        imageNote: "د پروفایل انځور به د لارښوونې لارښود کې وښودل شي",
        add: "اضافه کول",
        removeProfile: "د لارښود پروفایل لرې کول",
      },
      alerts: {
        removeApplicationTitle: "غوښتنلیک لرې کول؟",
        removeApplicationHtml: "ایا تاسو ډاډه یاست چې غواړئ خپل غوښتنلیک د <strong>{{title}}</strong> لپاره لرې کړئ؟",
        yesRemove: "هو، لرې یې کړئ",
        cancel: "لغوه",
        applicationRemovedTitle: "غوښتنلیک لرې شو",
        applicationRemovedText: "ستاسو د دندې غوښتنلیک په بریالیتوب سره لرې شو.",
        error: "تېروتنه",
        removeApplicationError: "د غوښتنلیک لرې کول ناکام شول. مهرباني وکړئ بیا هڅه وکړئ.",
        saveMentorError: "د لارښود پروفایل ثبتول ناکام شول.",
        mentorSavedTitle: "د لارښود پروفایل ثبت شو!",
        removeMentorTitle: "د لارښود پروفایل لرې کول؟",
        removeMentorText: "تاسو به نور د لارښوونې لارښود کې ښکاره نه شئ.",
        yesRemoveShort: "هو، لرې یې کړئ",
        removeMentorError: "د لارښود پروفایل لرې کول ناکام شول.",
        requestMentorshipTitle: "د لارښوونې غوښتنه",
        requestMentorshipIntro: "<strong>{{name}}</strong> ته غوښتنه ولیږئ",
        whatsappPlaceholder: "د واتساپ شمیره (اختیاري)",
        introducePlaceholder: "ځان معرفي کړئ او تشریح کړئ چې په څه کې لارښوونه غواړئ... (اختیاري)",
        sendRequest: "غوښتنه ولیږئ",
        requestSentTitle: "غوښتنه ولیږل شوه!",
        requestSentText: "ستاسو د لارښوونې غوښتنه {{name}} ته ولیږل شوه. هغوی به ډېر ژر تاسو سره اړیکه ونیسي.",
        alreadyRequestedTitle: "مخکې غوښتنه شوې",
        sendRequestError: "د غوښتنې لیږل ناکام شول.",
        saveChangesError: "د بدلونونو ثبتول ناکام شول.",
        saveExperienceError: "د تجربې ثبتول ناکام شول.",
        areYouSure: "ایا تاسو ډاډه یاست؟",
        deleteExperienceText: "ایا غواړئ دا تجربه ړنګه کړئ؟",
        yesDelete: "هو، ړنګه یې کړئ!",
        deletedTitle: "ړنګ شو!",
        experienceDeleted: "تجربه ړنګه شوه.",
        deleteExperienceError: "د تجربې ړنګول ناکام شول.",
        saveEducationError: "د زده‌کړې ثبتول ناکام شول.",
        deleteEducationText: "ایا غواړئ دا زده‌کړه ړنګه کړئ؟",
        educationDeleted: "زده‌کړه ړنګه شوه.",
        deleteEducationError: "د زده‌کړې ړنګول ناکام شول.",
        saveSkillError: "د مهارت ثبتول ناکام شول.",
        deleteSkillText: "ایا غواړئ دا مهارت ړنګ کړئ؟",
        skillDeleted: "مهارت ړنګ شو.",
        deleteSkillError: "د مهارت ړنګول ناکام شول.",
        saveAchievementError: "د لاسته‌راوړنې ثبتول ناکام شول.",
        deleteAchievementText: "ایا غواړئ دا لاسته‌راوړنه ړنګه کړئ؟",
        achievementDeleted: "لاسته‌راوړنه ړنګه شوه.",
        deleteAchievementError: "د لاسته‌راوړنې ړنګول ناکام شول.",
        updateContactError: "د اړیکې معلوماتو تازه کول ناکام شول.",
        deleteContactText: "ایا غواړئ خپل د {{field}} معلومات لرې کړئ؟",
        yesRemoveIt: "هو، لرې یې کړئ!",
        removedTitle: "لرې شو!",
        contactRemoved: "د {{field}} معلومات لرې شول.",
        removeContactError: "د اړیکې معلوماتو لرې کول ناکام شول.",
        acceptMentorshipTitle: "لارښوونه منل",
        acceptMentorshipHtml: "د لارښوونې د پای نېټه وټاکئ. له دې نېټې وروسته، <strong>{{name}}</strong> باید بیا غوښتنه وکړي.",
        accept: "منل",
        pickEndDate: "مهرباني وکړئ د پای نېټه وټاکئ",
        endDateFuture: "د پای نېټه باید په راتلونکي کې وي",
        acceptedTitle: "ومنل شو",
        mentorshipActiveUntil: "لارښوونه تر {{date}} پورې فعاله",
        failed: "ناکام شو",
        rejectedTitle: "رد شو",
      },
    },
  },
};

export default profile;
